# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import rpc_pb2 as rpc__pb2


class LonghornEngineServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.EngineCreate = channel.unary_unary(
        '/LonghornEngineService/EngineCreate',
        request_serializer=rpc__pb2.EngineCreateRequest.SerializeToString,
        response_deserializer=rpc__pb2.EngineResponse.FromString,
        )
    self.EngineDelete = channel.unary_unary(
        '/LonghornEngineService/EngineDelete',
        request_serializer=rpc__pb2.EngineRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.EngineGet = channel.unary_unary(
        '/LonghornEngineService/EngineGet',
        request_serializer=rpc__pb2.EngineRequest.SerializeToString,
        response_deserializer=rpc__pb2.EngineResponse.FromString,
        )
    self.EngineList = channel.unary_unary(
        '/LonghornEngineService/EngineList',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=rpc__pb2.EngineListResponse.FromString,
        )
    self.EngineUpgrade = channel.unary_unary(
        '/LonghornEngineService/EngineUpgrade',
        request_serializer=rpc__pb2.EngineUpgradeRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.FrontendStart = channel.unary_unary(
        '/LonghornEngineService/FrontendStart',
        request_serializer=rpc__pb2.FrontendStartRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.FrontendShutdown = channel.unary_unary(
        '/LonghornEngineService/FrontendShutdown',
        request_serializer=rpc__pb2.FrontendShutdownRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.FrontendStartCallback = channel.unary_unary(
        '/LonghornEngineService/FrontendStartCallback',
        request_serializer=rpc__pb2.EngineRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.FrontendShutdownCallback = channel.unary_unary(
        '/LonghornEngineService/FrontendShutdownCallback',
        request_serializer=rpc__pb2.EngineRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )


class LonghornEngineServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def EngineCreate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def EngineDelete(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def EngineGet(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def EngineList(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def EngineUpgrade(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FrontendStart(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FrontendShutdown(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FrontendStartCallback(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FrontendShutdownCallback(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_LonghornEngineServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'EngineCreate': grpc.unary_unary_rpc_method_handler(
          servicer.EngineCreate,
          request_deserializer=rpc__pb2.EngineCreateRequest.FromString,
          response_serializer=rpc__pb2.EngineResponse.SerializeToString,
      ),
      'EngineDelete': grpc.unary_unary_rpc_method_handler(
          servicer.EngineDelete,
          request_deserializer=rpc__pb2.EngineRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'EngineGet': grpc.unary_unary_rpc_method_handler(
          servicer.EngineGet,
          request_deserializer=rpc__pb2.EngineRequest.FromString,
          response_serializer=rpc__pb2.EngineResponse.SerializeToString,
      ),
      'EngineList': grpc.unary_unary_rpc_method_handler(
          servicer.EngineList,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=rpc__pb2.EngineListResponse.SerializeToString,
      ),
      'EngineUpgrade': grpc.unary_unary_rpc_method_handler(
          servicer.EngineUpgrade,
          request_deserializer=rpc__pb2.EngineUpgradeRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'FrontendStart': grpc.unary_unary_rpc_method_handler(
          servicer.FrontendStart,
          request_deserializer=rpc__pb2.FrontendStartRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'FrontendShutdown': grpc.unary_unary_rpc_method_handler(
          servicer.FrontendShutdown,
          request_deserializer=rpc__pb2.FrontendShutdownRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'FrontendStartCallback': grpc.unary_unary_rpc_method_handler(
          servicer.FrontendStartCallback,
          request_deserializer=rpc__pb2.EngineRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'FrontendShutdownCallback': grpc.unary_unary_rpc_method_handler(
          servicer.FrontendShutdownCallback,
          request_deserializer=rpc__pb2.EngineRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'LonghornEngineService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class LonghornProcessLauncherServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ProcessCreate = channel.unary_unary(
        '/LonghornProcessLauncherService/ProcessCreate',
        request_serializer=rpc__pb2.ProcessCreateRequest.SerializeToString,
        response_deserializer=rpc__pb2.ProcessResponse.FromString,
        )
    self.ProcessDelete = channel.unary_unary(
        '/LonghornProcessLauncherService/ProcessDelete',
        request_serializer=rpc__pb2.ProcessDeleteRequest.SerializeToString,
        response_deserializer=rpc__pb2.ProcessResponse.FromString,
        )
    self.ProcessGet = channel.unary_unary(
        '/LonghornProcessLauncherService/ProcessGet',
        request_serializer=rpc__pb2.ProcessGetRequest.SerializeToString,
        response_deserializer=rpc__pb2.ProcessResponse.FromString,
        )
    self.ProcessList = channel.unary_unary(
        '/LonghornProcessLauncherService/ProcessList',
        request_serializer=rpc__pb2.ProcessListRequest.SerializeToString,
        response_deserializer=rpc__pb2.ProcessListResponse.FromString,
        )


class LonghornProcessLauncherServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ProcessCreate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ProcessDelete(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ProcessGet(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ProcessList(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_LonghornProcessLauncherServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ProcessCreate': grpc.unary_unary_rpc_method_handler(
          servicer.ProcessCreate,
          request_deserializer=rpc__pb2.ProcessCreateRequest.FromString,
          response_serializer=rpc__pb2.ProcessResponse.SerializeToString,
      ),
      'ProcessDelete': grpc.unary_unary_rpc_method_handler(
          servicer.ProcessDelete,
          request_deserializer=rpc__pb2.ProcessDeleteRequest.FromString,
          response_serializer=rpc__pb2.ProcessResponse.SerializeToString,
      ),
      'ProcessGet': grpc.unary_unary_rpc_method_handler(
          servicer.ProcessGet,
          request_deserializer=rpc__pb2.ProcessGetRequest.FromString,
          response_serializer=rpc__pb2.ProcessResponse.SerializeToString,
      ),
      'ProcessList': grpc.unary_unary_rpc_method_handler(
          servicer.ProcessList,
          request_deserializer=rpc__pb2.ProcessListRequest.FromString,
          response_serializer=rpc__pb2.ProcessListResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'LonghornProcessLauncherService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
