---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: default
  image: rancher/dapper:1.10.3
  commands:
  - dapper ci
  privileged: true
  volumes:
  - name: socket
    path: /var/run/docker.sock

- name: docker-publish-master
  pull: default
  image: plugins/docker
  settings:
    context: package/
    custom_dns: 1.1.1.1
    dockerfile: package/Dockerfile
    password:
      from_secret: docker_password
    repo: rancher/longhorn-engine
    tag: master
    username:
      from_secret: docker_username
  when:
    branch:
    - master
    event:
    - push

volumes:
- name: socket
  host:
    path: /var/run/docker.sock
