// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc.proto

package rpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FileRemoveRequest struct {
	FileName             string   `protobuf:"bytes,1,opt,name=fileName,proto3" json:"fileName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileRemoveRequest) Reset()         { *m = FileRemoveRequest{} }
func (m *FileRemoveRequest) String() string { return proto.CompactTextString(m) }
func (*FileRemoveRequest) ProtoMessage()    {}
func (*FileRemoveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{0}
}

func (m *FileRemoveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileRemoveRequest.Unmarshal(m, b)
}
func (m *FileRemoveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileRemoveRequest.Marshal(b, m, deterministic)
}
func (m *FileRemoveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileRemoveRequest.Merge(m, src)
}
func (m *FileRemoveRequest) XXX_Size() int {
	return xxx_messageInfo_FileRemoveRequest.Size(m)
}
func (m *FileRemoveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FileRemoveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FileRemoveRequest proto.InternalMessageInfo

func (m *FileRemoveRequest) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

type FileRenameRequest struct {
	OldFileName          string   `protobuf:"bytes,1,opt,name=oldFileName,proto3" json:"oldFileName,omitempty"`
	NewFileName          string   `protobuf:"bytes,2,opt,name=newFileName,proto3" json:"newFileName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileRenameRequest) Reset()         { *m = FileRenameRequest{} }
func (m *FileRenameRequest) String() string { return proto.CompactTextString(m) }
func (*FileRenameRequest) ProtoMessage()    {}
func (*FileRenameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{1}
}

func (m *FileRenameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileRenameRequest.Unmarshal(m, b)
}
func (m *FileRenameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileRenameRequest.Marshal(b, m, deterministic)
}
func (m *FileRenameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileRenameRequest.Merge(m, src)
}
func (m *FileRenameRequest) XXX_Size() int {
	return xxx_messageInfo_FileRenameRequest.Size(m)
}
func (m *FileRenameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FileRenameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FileRenameRequest proto.InternalMessageInfo

func (m *FileRenameRequest) GetOldFileName() string {
	if m != nil {
		return m.OldFileName
	}
	return ""
}

func (m *FileRenameRequest) GetNewFileName() string {
	if m != nil {
		return m.NewFileName
	}
	return ""
}

type ReceiverLaunchRequest struct {
	ToFileName           string   `protobuf:"bytes,1,opt,name=toFileName,proto3" json:"toFileName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReceiverLaunchRequest) Reset()         { *m = ReceiverLaunchRequest{} }
func (m *ReceiverLaunchRequest) String() string { return proto.CompactTextString(m) }
func (*ReceiverLaunchRequest) ProtoMessage()    {}
func (*ReceiverLaunchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{2}
}

func (m *ReceiverLaunchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiverLaunchRequest.Unmarshal(m, b)
}
func (m *ReceiverLaunchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiverLaunchRequest.Marshal(b, m, deterministic)
}
func (m *ReceiverLaunchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiverLaunchRequest.Merge(m, src)
}
func (m *ReceiverLaunchRequest) XXX_Size() int {
	return xxx_messageInfo_ReceiverLaunchRequest.Size(m)
}
func (m *ReceiverLaunchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiverLaunchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiverLaunchRequest proto.InternalMessageInfo

func (m *ReceiverLaunchRequest) GetToFileName() string {
	if m != nil {
		return m.ToFileName
	}
	return ""
}

type ReceiverLaunchReply struct {
	Port                 int32    `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReceiverLaunchReply) Reset()         { *m = ReceiverLaunchReply{} }
func (m *ReceiverLaunchReply) String() string { return proto.CompactTextString(m) }
func (*ReceiverLaunchReply) ProtoMessage()    {}
func (*ReceiverLaunchReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{3}
}

func (m *ReceiverLaunchReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiverLaunchReply.Unmarshal(m, b)
}
func (m *ReceiverLaunchReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiverLaunchReply.Marshal(b, m, deterministic)
}
func (m *ReceiverLaunchReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiverLaunchReply.Merge(m, src)
}
func (m *ReceiverLaunchReply) XXX_Size() int {
	return xxx_messageInfo_ReceiverLaunchReply.Size(m)
}
func (m *ReceiverLaunchReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiverLaunchReply.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiverLaunchReply proto.InternalMessageInfo

func (m *ReceiverLaunchReply) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type FileSendRequest struct {
	FromFileName         string   `protobuf:"bytes,1,opt,name=fromFileName,proto3" json:"fromFileName,omitempty"`
	Host                 string   `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port                 int32    `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileSendRequest) Reset()         { *m = FileSendRequest{} }
func (m *FileSendRequest) String() string { return proto.CompactTextString(m) }
func (*FileSendRequest) ProtoMessage()    {}
func (*FileSendRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{4}
}

func (m *FileSendRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileSendRequest.Unmarshal(m, b)
}
func (m *FileSendRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileSendRequest.Marshal(b, m, deterministic)
}
func (m *FileSendRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileSendRequest.Merge(m, src)
}
func (m *FileSendRequest) XXX_Size() int {
	return xxx_messageInfo_FileSendRequest.Size(m)
}
func (m *FileSendRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FileSendRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FileSendRequest proto.InternalMessageInfo

func (m *FileSendRequest) GetFromFileName() string {
	if m != nil {
		return m.FromFileName
	}
	return ""
}

func (m *FileSendRequest) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *FileSendRequest) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type FileCoalesceRequest struct {
	FromFileName         string   `protobuf:"bytes,1,opt,name=fromFileName,proto3" json:"fromFileName,omitempty"`
	ToFileName           string   `protobuf:"bytes,2,opt,name=toFileName,proto3" json:"toFileName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileCoalesceRequest) Reset()         { *m = FileCoalesceRequest{} }
func (m *FileCoalesceRequest) String() string { return proto.CompactTextString(m) }
func (*FileCoalesceRequest) ProtoMessage()    {}
func (*FileCoalesceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{5}
}

func (m *FileCoalesceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileCoalesceRequest.Unmarshal(m, b)
}
func (m *FileCoalesceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileCoalesceRequest.Marshal(b, m, deterministic)
}
func (m *FileCoalesceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileCoalesceRequest.Merge(m, src)
}
func (m *FileCoalesceRequest) XXX_Size() int {
	return xxx_messageInfo_FileCoalesceRequest.Size(m)
}
func (m *FileCoalesceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FileCoalesceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FileCoalesceRequest proto.InternalMessageInfo

func (m *FileCoalesceRequest) GetFromFileName() string {
	if m != nil {
		return m.FromFileName
	}
	return ""
}

func (m *FileCoalesceRequest) GetToFileName() string {
	if m != nil {
		return m.ToFileName
	}
	return ""
}

type BackupCreateRequest struct {
	SnapshotFileName     string            `protobuf:"bytes,1,opt,name=snapshotFileName,proto3" json:"snapshotFileName,omitempty"`
	BackupTarget         string            `protobuf:"bytes,2,opt,name=backupTarget,proto3" json:"backupTarget,omitempty"`
	VolumeName           string            `protobuf:"bytes,3,opt,name=volumeName,proto3" json:"volumeName,omitempty"`
	Labels               []string          `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty"`
	Credential           map[string]string `protobuf:"bytes,5,rep,name=credential,proto3" json:"credential,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *BackupCreateRequest) Reset()         { *m = BackupCreateRequest{} }
func (m *BackupCreateRequest) String() string { return proto.CompactTextString(m) }
func (*BackupCreateRequest) ProtoMessage()    {}
func (*BackupCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{6}
}

func (m *BackupCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackupCreateRequest.Unmarshal(m, b)
}
func (m *BackupCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackupCreateRequest.Marshal(b, m, deterministic)
}
func (m *BackupCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackupCreateRequest.Merge(m, src)
}
func (m *BackupCreateRequest) XXX_Size() int {
	return xxx_messageInfo_BackupCreateRequest.Size(m)
}
func (m *BackupCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BackupCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BackupCreateRequest proto.InternalMessageInfo

func (m *BackupCreateRequest) GetSnapshotFileName() string {
	if m != nil {
		return m.SnapshotFileName
	}
	return ""
}

func (m *BackupCreateRequest) GetBackupTarget() string {
	if m != nil {
		return m.BackupTarget
	}
	return ""
}

func (m *BackupCreateRequest) GetVolumeName() string {
	if m != nil {
		return m.VolumeName
	}
	return ""
}

func (m *BackupCreateRequest) GetLabels() []string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *BackupCreateRequest) GetCredential() map[string]string {
	if m != nil {
		return m.Credential
	}
	return nil
}

type BackupCreateReply struct {
	Backup               string   `protobuf:"bytes,1,opt,name=backup,proto3" json:"backup,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BackupCreateReply) Reset()         { *m = BackupCreateReply{} }
func (m *BackupCreateReply) String() string { return proto.CompactTextString(m) }
func (*BackupCreateReply) ProtoMessage()    {}
func (*BackupCreateReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{7}
}

func (m *BackupCreateReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackupCreateReply.Unmarshal(m, b)
}
func (m *BackupCreateReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackupCreateReply.Marshal(b, m, deterministic)
}
func (m *BackupCreateReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackupCreateReply.Merge(m, src)
}
func (m *BackupCreateReply) XXX_Size() int {
	return xxx_messageInfo_BackupCreateReply.Size(m)
}
func (m *BackupCreateReply) XXX_DiscardUnknown() {
	xxx_messageInfo_BackupCreateReply.DiscardUnknown(m)
}

var xxx_messageInfo_BackupCreateReply proto.InternalMessageInfo

func (m *BackupCreateReply) GetBackup() string {
	if m != nil {
		return m.Backup
	}
	return ""
}

type BackupRemoveRequest struct {
	Backup               string   `protobuf:"bytes,1,opt,name=backup,proto3" json:"backup,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BackupRemoveRequest) Reset()         { *m = BackupRemoveRequest{} }
func (m *BackupRemoveRequest) String() string { return proto.CompactTextString(m) }
func (*BackupRemoveRequest) ProtoMessage()    {}
func (*BackupRemoveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{8}
}

func (m *BackupRemoveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackupRemoveRequest.Unmarshal(m, b)
}
func (m *BackupRemoveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackupRemoveRequest.Marshal(b, m, deterministic)
}
func (m *BackupRemoveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackupRemoveRequest.Merge(m, src)
}
func (m *BackupRemoveRequest) XXX_Size() int {
	return xxx_messageInfo_BackupRemoveRequest.Size(m)
}
func (m *BackupRemoveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BackupRemoveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BackupRemoveRequest proto.InternalMessageInfo

func (m *BackupRemoveRequest) GetBackup() string {
	if m != nil {
		return m.Backup
	}
	return ""
}

type BackupProgressRequest struct {
	Backup               string   `protobuf:"bytes,1,opt,name=backup,proto3" json:"backup,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BackupProgressRequest) Reset()         { *m = BackupProgressRequest{} }
func (m *BackupProgressRequest) String() string { return proto.CompactTextString(m) }
func (*BackupProgressRequest) ProtoMessage()    {}
func (*BackupProgressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{9}
}

func (m *BackupProgressRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackupProgressRequest.Unmarshal(m, b)
}
func (m *BackupProgressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackupProgressRequest.Marshal(b, m, deterministic)
}
func (m *BackupProgressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackupProgressRequest.Merge(m, src)
}
func (m *BackupProgressRequest) XXX_Size() int {
	return xxx_messageInfo_BackupProgressRequest.Size(m)
}
func (m *BackupProgressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BackupProgressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BackupProgressRequest proto.InternalMessageInfo

func (m *BackupProgressRequest) GetBackup() string {
	if m != nil {
		return m.Backup
	}
	return ""
}

type BackupProgressReply struct {
	Progress             int32    `protobuf:"varint,1,opt,name=progress,proto3" json:"progress,omitempty"`
	BackupURL            string   `protobuf:"bytes,2,opt,name=backupURL,proto3" json:"backupURL,omitempty"`
	BackupError          string   `protobuf:"bytes,3,opt,name=backupError,proto3" json:"backupError,omitempty"`
	SnapshotName         string   `protobuf:"bytes,4,opt,name=snapshotName,proto3" json:"snapshotName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BackupProgressReply) Reset()         { *m = BackupProgressReply{} }
func (m *BackupProgressReply) String() string { return proto.CompactTextString(m) }
func (*BackupProgressReply) ProtoMessage()    {}
func (*BackupProgressReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{10}
}

func (m *BackupProgressReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackupProgressReply.Unmarshal(m, b)
}
func (m *BackupProgressReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackupProgressReply.Marshal(b, m, deterministic)
}
func (m *BackupProgressReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackupProgressReply.Merge(m, src)
}
func (m *BackupProgressReply) XXX_Size() int {
	return xxx_messageInfo_BackupProgressReply.Size(m)
}
func (m *BackupProgressReply) XXX_DiscardUnknown() {
	xxx_messageInfo_BackupProgressReply.DiscardUnknown(m)
}

var xxx_messageInfo_BackupProgressReply proto.InternalMessageInfo

func (m *BackupProgressReply) GetProgress() int32 {
	if m != nil {
		return m.Progress
	}
	return 0
}

func (m *BackupProgressReply) GetBackupURL() string {
	if m != nil {
		return m.BackupURL
	}
	return ""
}

func (m *BackupProgressReply) GetBackupError() string {
	if m != nil {
		return m.BackupError
	}
	return ""
}

func (m *BackupProgressReply) GetSnapshotName() string {
	if m != nil {
		return m.SnapshotName
	}
	return ""
}

type BackupRestoreRequest struct {
	Backup               string            `protobuf:"bytes,1,opt,name=backup,proto3" json:"backup,omitempty"`
	SnapshotFileName     string            `protobuf:"bytes,2,opt,name=snapshotFileName,proto3" json:"snapshotFileName,omitempty"`
	Credential           map[string]string `protobuf:"bytes,3,rep,name=credential,proto3" json:"credential,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *BackupRestoreRequest) Reset()         { *m = BackupRestoreRequest{} }
func (m *BackupRestoreRequest) String() string { return proto.CompactTextString(m) }
func (*BackupRestoreRequest) ProtoMessage()    {}
func (*BackupRestoreRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{11}
}

func (m *BackupRestoreRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackupRestoreRequest.Unmarshal(m, b)
}
func (m *BackupRestoreRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackupRestoreRequest.Marshal(b, m, deterministic)
}
func (m *BackupRestoreRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackupRestoreRequest.Merge(m, src)
}
func (m *BackupRestoreRequest) XXX_Size() int {
	return xxx_messageInfo_BackupRestoreRequest.Size(m)
}
func (m *BackupRestoreRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BackupRestoreRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BackupRestoreRequest proto.InternalMessageInfo

func (m *BackupRestoreRequest) GetBackup() string {
	if m != nil {
		return m.Backup
	}
	return ""
}

func (m *BackupRestoreRequest) GetSnapshotFileName() string {
	if m != nil {
		return m.SnapshotFileName
	}
	return ""
}

func (m *BackupRestoreRequest) GetCredential() map[string]string {
	if m != nil {
		return m.Credential
	}
	return nil
}

type BackupRestoreIncrementallyRequest struct {
	Backup                 string            `protobuf:"bytes,1,opt,name=backup,proto3" json:"backup,omitempty"`
	DeltaFileName          string            `protobuf:"bytes,2,opt,name=deltaFileName,proto3" json:"deltaFileName,omitempty"`
	LastRestoredBackupName string            `protobuf:"bytes,3,opt,name=lastRestoredBackupName,proto3" json:"lastRestoredBackupName,omitempty"`
	Credential             map[string]string `protobuf:"bytes,4,rep,name=credential,proto3" json:"credential,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral   struct{}          `json:"-"`
	XXX_unrecognized       []byte            `json:"-"`
	XXX_sizecache          int32             `json:"-"`
}

func (m *BackupRestoreIncrementallyRequest) Reset()         { *m = BackupRestoreIncrementallyRequest{} }
func (m *BackupRestoreIncrementallyRequest) String() string { return proto.CompactTextString(m) }
func (*BackupRestoreIncrementallyRequest) ProtoMessage()    {}
func (*BackupRestoreIncrementallyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{12}
}

func (m *BackupRestoreIncrementallyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackupRestoreIncrementallyRequest.Unmarshal(m, b)
}
func (m *BackupRestoreIncrementallyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackupRestoreIncrementallyRequest.Marshal(b, m, deterministic)
}
func (m *BackupRestoreIncrementallyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackupRestoreIncrementallyRequest.Merge(m, src)
}
func (m *BackupRestoreIncrementallyRequest) XXX_Size() int {
	return xxx_messageInfo_BackupRestoreIncrementallyRequest.Size(m)
}
func (m *BackupRestoreIncrementallyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BackupRestoreIncrementallyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BackupRestoreIncrementallyRequest proto.InternalMessageInfo

func (m *BackupRestoreIncrementallyRequest) GetBackup() string {
	if m != nil {
		return m.Backup
	}
	return ""
}

func (m *BackupRestoreIncrementallyRequest) GetDeltaFileName() string {
	if m != nil {
		return m.DeltaFileName
	}
	return ""
}

func (m *BackupRestoreIncrementallyRequest) GetLastRestoredBackupName() string {
	if m != nil {
		return m.LastRestoredBackupName
	}
	return ""
}

func (m *BackupRestoreIncrementallyRequest) GetCredential() map[string]string {
	if m != nil {
		return m.Credential
	}
	return nil
}

type RestoreStatusReply struct {
	IsRestoring          bool     `protobuf:"varint,1,opt,name=isRestoring,proto3" json:"isRestoring,omitempty"`
	LastRestored         string   `protobuf:"bytes,2,opt,name=lastRestored,proto3" json:"lastRestored,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RestoreStatusReply) Reset()         { *m = RestoreStatusReply{} }
func (m *RestoreStatusReply) String() string { return proto.CompactTextString(m) }
func (*RestoreStatusReply) ProtoMessage()    {}
func (*RestoreStatusReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{13}
}

func (m *RestoreStatusReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestoreStatusReply.Unmarshal(m, b)
}
func (m *RestoreStatusReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestoreStatusReply.Marshal(b, m, deterministic)
}
func (m *RestoreStatusReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestoreStatusReply.Merge(m, src)
}
func (m *RestoreStatusReply) XXX_Size() int {
	return xxx_messageInfo_RestoreStatusReply.Size(m)
}
func (m *RestoreStatusReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RestoreStatusReply.DiscardUnknown(m)
}

var xxx_messageInfo_RestoreStatusReply proto.InternalMessageInfo

func (m *RestoreStatusReply) GetIsRestoring() bool {
	if m != nil {
		return m.IsRestoring
	}
	return false
}

func (m *RestoreStatusReply) GetLastRestored() string {
	if m != nil {
		return m.LastRestored
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{14}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*FileRemoveRequest)(nil), "FileRemoveRequest")
	proto.RegisterType((*FileRenameRequest)(nil), "FileRenameRequest")
	proto.RegisterType((*ReceiverLaunchRequest)(nil), "ReceiverLaunchRequest")
	proto.RegisterType((*ReceiverLaunchReply)(nil), "ReceiverLaunchReply")
	proto.RegisterType((*FileSendRequest)(nil), "FileSendRequest")
	proto.RegisterType((*FileCoalesceRequest)(nil), "FileCoalesceRequest")
	proto.RegisterType((*BackupCreateRequest)(nil), "BackupCreateRequest")
	proto.RegisterMapType((map[string]string)(nil), "BackupCreateRequest.CredentialEntry")
	proto.RegisterType((*BackupCreateReply)(nil), "BackupCreateReply")
	proto.RegisterType((*BackupRemoveRequest)(nil), "BackupRemoveRequest")
	proto.RegisterType((*BackupProgressRequest)(nil), "BackupProgressRequest")
	proto.RegisterType((*BackupProgressReply)(nil), "BackupProgressReply")
	proto.RegisterType((*BackupRestoreRequest)(nil), "BackupRestoreRequest")
	proto.RegisterMapType((map[string]string)(nil), "BackupRestoreRequest.CredentialEntry")
	proto.RegisterType((*BackupRestoreIncrementallyRequest)(nil), "BackupRestoreIncrementallyRequest")
	proto.RegisterMapType((map[string]string)(nil), "BackupRestoreIncrementallyRequest.CredentialEntry")
	proto.RegisterType((*RestoreStatusReply)(nil), "RestoreStatusReply")
	proto.RegisterType((*Empty)(nil), "Empty")
}

func init() { proto.RegisterFile("rpc.proto", fileDescriptor_77a6da22d6a3feb1) }

var fileDescriptor_77a6da22d6a3feb1 = []byte{
	// 756 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xdd, 0x6a, 0x13, 0x41,
	0x14, 0xce, 0xbf, 0xc9, 0x69, 0x6b, 0xd3, 0x49, 0x1a, 0xea, 0x22, 0x12, 0x87, 0x2a, 0xb5, 0xe2,
	0x54, 0x2a, 0xa8, 0x14, 0x04, 0x6b, 0x4d, 0x45, 0x29, 0x22, 0x1b, 0x45, 0x14, 0xbc, 0x98, 0x6e,
	0x4e, 0xd3, 0xd0, 0xcd, 0xee, 0x3a, 0x3b, 0x89, 0xe4, 0x41, 0x7c, 0x01, 0xaf, 0x7d, 0x28, 0x1f,
	0xc4, 0x0b, 0xd9, 0xdf, 0xcc, 0x6c, 0x36, 0x04, 0x2f, 0x7a, 0xb7, 0xf3, 0xe5, 0x7c, 0xdf, 0x99,
	0x33, 0xf3, 0xcd, 0x39, 0x81, 0x86, 0xf0, 0x2c, 0xe6, 0x09, 0x57, 0xba, 0xf4, 0x00, 0xb6, 0x4e,
	0x47, 0x36, 0x9a, 0x38, 0x76, 0xa7, 0x68, 0xe2, 0xf7, 0x09, 0xfa, 0x92, 0x18, 0x50, 0xbf, 0x18,
	0xd9, 0xf8, 0x9e, 0x8f, 0x71, 0xa7, 0xd8, 0x2d, 0xee, 0x35, 0xcc, 0x74, 0x4d, 0x3f, 0x27, 0x04,
	0x87, 0x8f, 0x53, 0x42, 0x17, 0xd6, 0x5c, 0x7b, 0x70, 0xaa, 0x73, 0x54, 0x28, 0x88, 0x70, 0xf0,
	0x47, 0x1a, 0x51, 0x8a, 0x22, 0x14, 0x88, 0x3e, 0x83, 0x6d, 0x13, 0x2d, 0x1c, 0x4d, 0x51, 0x9c,
	0xf1, 0x89, 0x63, 0x5d, 0x26, 0xe2, 0x77, 0x00, 0xa4, 0x9b, 0xd1, 0x56, 0x10, 0xfa, 0x00, 0x5a,
	0x59, 0xa2, 0x67, 0xcf, 0x08, 0x81, 0x8a, 0xe7, 0x0a, 0x19, 0x12, 0xaa, 0x66, 0xf8, 0x4d, 0xbf,
	0xc1, 0x66, 0x40, 0xeb, 0xa3, 0x33, 0x48, 0xd4, 0x29, 0xac, 0x5f, 0x08, 0x77, 0x9c, 0xd1, 0xd7,
	0xb0, 0x40, 0xea, 0xd2, 0xf5, 0x65, 0xbc, 0xeb, 0xf0, 0x3b, 0x95, 0x2f, 0x2b, 0xf2, 0x5f, 0xa0,
	0x15, 0x70, 0x4e, 0x5c, 0x6e, 0xa3, 0x6f, 0xe1, 0xff, 0xa4, 0xd0, 0x8b, 0x2c, 0x2d, 0x14, 0xf9,
	0xab, 0x04, 0xad, 0x57, 0xdc, 0xba, 0x9a, 0x78, 0x27, 0x02, 0xb9, 0x4c, 0xb5, 0xf7, 0xa1, 0xe9,
	0x3b, 0xdc, 0xf3, 0x2f, 0x5d, 0x99, 0xd1, 0x5f, 0xc0, 0x83, 0x7d, 0x9c, 0x87, 0x12, 0x1f, 0xb9,
	0x18, 0x62, 0x52, 0x8e, 0x86, 0x05, 0xfb, 0x98, 0xba, 0xf6, 0x64, 0x1c, 0x29, 0x95, 0xa3, 0x7d,
	0xcc, 0x11, 0xd2, 0x81, 0x9a, 0xcd, 0xcf, 0xd1, 0xf6, 0x77, 0x2a, 0xdd, 0xf2, 0x5e, 0xc3, 0x8c,
	0x57, 0xe4, 0x35, 0x80, 0x25, 0x70, 0x80, 0x8e, 0x1c, 0x71, 0x7b, 0xa7, 0xda, 0x2d, 0xef, 0xad,
	0x1d, 0xee, 0xb2, 0x9c, 0x1d, 0xb3, 0x93, 0x34, 0xac, 0xe7, 0x48, 0x31, 0x33, 0x15, 0x9e, 0xf1,
	0x02, 0x36, 0x33, 0x3f, 0x93, 0x26, 0x94, 0xaf, 0x70, 0x16, 0xd7, 0x14, 0x7c, 0x92, 0x36, 0x54,
	0xa7, 0xdc, 0x9e, 0x24, 0xa7, 0x14, 0x2d, 0x8e, 0x4a, 0xcf, 0x8b, 0xf4, 0x21, 0x6c, 0xe9, 0x19,
	0x03, 0x1f, 0x74, 0xa0, 0x16, 0x55, 0x18, 0x6b, 0xc4, 0x2b, 0xfa, 0x28, 0x39, 0x50, 0xdd, 0xfb,
	0xcb, 0xc2, 0x0f, 0x60, 0x3b, 0x0a, 0xff, 0x20, 0xdc, 0xa1, 0x40, 0xdf, 0x5f, 0x45, 0xf8, 0x59,
	0x4c, 0x12, 0xcc, 0x19, 0xc1, 0x7e, 0x0c, 0xa8, 0x7b, 0x31, 0x10, 0x7b, 0x33, 0x5d, 0x93, 0xdb,
	0xd0, 0x88, 0xd8, 0x9f, 0xcc, 0xb3, 0xb8, 0xbc, 0x39, 0x10, 0xbc, 0xa1, 0x68, 0xd1, 0x13, 0xc2,
	0x15, 0xf1, 0xe5, 0xa8, 0x50, 0x70, 0xc3, 0xc9, 0xad, 0x87, 0xf7, 0x57, 0x89, 0x6e, 0x58, 0xc5,
	0xe8, 0x9f, 0x22, 0xb4, 0x93, 0xc2, 0x7d, 0xe9, 0x8a, 0x55, 0x95, 0xe7, 0x5a, 0xac, 0xb4, 0xc4,
	0x62, 0x3d, 0xcd, 0x06, 0xe5, 0xd0, 0x06, 0xf7, 0x58, 0x5e, 0xba, 0xeb, 0xf4, 0xc1, 0xef, 0x12,
	0xdc, 0xd5, 0x72, 0xbe, 0x75, 0x2c, 0x81, 0x63, 0x74, 0x24, 0xb7, 0xed, 0xd9, 0xaa, 0x7a, 0x77,
	0x61, 0x63, 0x80, 0xb6, 0xe4, 0x99, 0x62, 0x75, 0x90, 0x3c, 0x85, 0x8e, 0xcd, 0x7d, 0x19, 0x27,
	0x18, 0x44, 0xe9, 0x94, 0x47, 0xb3, 0xe4, 0x57, 0x62, 0x6a, 0x27, 0x54, 0x09, 0x4f, 0xe8, 0x90,
	0xad, 0xdc, 0xed, 0x75, 0x1e, 0xd7, 0x57, 0x20, 0x71, 0xe6, 0xbe, 0xe4, 0x72, 0x12, 0xfb, 0xb4,
	0x0b, 0x6b, 0x23, 0x3f, 0xc2, 0x47, 0xce, 0x30, 0x54, 0xaa, 0x9b, 0x2a, 0x14, 0xb8, 0x4d, 0x2d,
	0x32, 0xe9, 0x27, 0x2a, 0x46, 0x6f, 0x40, 0xb5, 0x37, 0xf6, 0xe4, 0xec, 0xf0, 0x6f, 0x05, 0x9a,
	0xfd, 0x99, 0x63, 0x1d, 0x0f, 0xd1, 0x91, 0x7d, 0x14, 0xd3, 0x91, 0x85, 0x64, 0x1f, 0x60, 0x3e,
	0x7d, 0x08, 0x61, 0x0b, 0xa3, 0xc8, 0xa8, 0xb1, 0x90, 0x4e, 0x0b, 0xf3, 0x58, 0x27, 0x6c, 0xc9,
	0x6c, 0x61, 0x0a, 0x29, 0xb1, 0x0c, 0xd6, 0xd5, 0x46, 0x4c, 0xda, 0x2c, 0xa7, 0x2f, 0x2b, 0xf1,
	0xf7, 0xa1, 0x9e, 0xcc, 0x05, 0xd2, 0x64, 0x99, 0x11, 0xa1, 0xc4, 0xbd, 0x84, 0x9b, 0xfa, 0xa8,
	0x21, 0x1d, 0x96, 0x3b, 0xb4, 0x8c, 0x36, 0xcb, 0x99, 0x49, 0xb4, 0x40, 0x8e, 0x60, 0x5d, 0x6d,
	0x51, 0xa4, 0x9d, 0xd7, 0x23, 0x0d, 0xc2, 0x16, 0xfa, 0x58, 0x54, 0x95, 0xda, 0xb1, 0x52, 0xee,
	0xb2, 0x13, 0x7b, 0x0c, 0x1b, 0x9a, 0xaf, 0xc8, 0x76, 0xee, 0x4b, 0x54, 0x18, 0xef, 0xc0, 0x58,
	0xee, 0x44, 0x42, 0x57, 0xdb, 0x54, 0xd1, 0x3a, 0x86, 0xcd, 0x28, 0xfc, 0x0d, 0xca, 0xc8, 0x57,
	0xa4, 0xc3, 0x72, 0x5b, 0xa8, 0xd1, 0x66, 0x39, 0x8d, 0x92, 0x16, 0xc8, 0x2d, 0xa8, 0x9a, 0xe8,
	0xa3, 0x24, 0xb1, 0xaa, 0x76, 0xc3, 0x1b, 0x9a, 0x67, 0xd3, 0x90, 0x16, 0x5b, 0xf4, 0x32, 0x2d,
	0x9c, 0xd7, 0xc2, 0xbf, 0x3b, 0x4f, 0xfe, 0x05, 0x00, 0x00, 0xff, 0xff, 0x49, 0x3a, 0x26, 0xa6,
	0xfb, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SyncAgentServiceClient is the client API for SyncAgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SyncAgentServiceClient interface {
	FileRemove(ctx context.Context, in *FileRemoveRequest, opts ...grpc.CallOption) (*Empty, error)
	FileRename(ctx context.Context, in *FileRenameRequest, opts ...grpc.CallOption) (*Empty, error)
	FileCoalesce(ctx context.Context, in *FileCoalesceRequest, opts ...grpc.CallOption) (*Empty, error)
	FileSend(ctx context.Context, in *FileSendRequest, opts ...grpc.CallOption) (*Empty, error)
	ReceiverLaunch(ctx context.Context, in *ReceiverLaunchRequest, opts ...grpc.CallOption) (*ReceiverLaunchReply, error)
	BackupCreate(ctx context.Context, in *BackupCreateRequest, opts ...grpc.CallOption) (*BackupCreateReply, error)
	BackupRemove(ctx context.Context, in *BackupRemoveRequest, opts ...grpc.CallOption) (*Empty, error)
	BackupRestore(ctx context.Context, in *BackupRestoreRequest, opts ...grpc.CallOption) (*Empty, error)
	BackupRestoreIncrementally(ctx context.Context, in *BackupRestoreIncrementallyRequest, opts ...grpc.CallOption) (*Empty, error)
	BackupGetStatus(ctx context.Context, in *BackupProgressRequest, opts ...grpc.CallOption) (*BackupProgressReply, error)
	Reset(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	RestoreStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RestoreStatusReply, error)
}

type syncAgentServiceClient struct {
	cc *grpc.ClientConn
}

func NewSyncAgentServiceClient(cc *grpc.ClientConn) SyncAgentServiceClient {
	return &syncAgentServiceClient{cc}
}

func (c *syncAgentServiceClient) FileRemove(ctx context.Context, in *FileRemoveRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/SyncAgentService/FileRemove", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncAgentServiceClient) FileRename(ctx context.Context, in *FileRenameRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/SyncAgentService/FileRename", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncAgentServiceClient) FileCoalesce(ctx context.Context, in *FileCoalesceRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/SyncAgentService/FileCoalesce", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncAgentServiceClient) FileSend(ctx context.Context, in *FileSendRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/SyncAgentService/FileSend", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncAgentServiceClient) ReceiverLaunch(ctx context.Context, in *ReceiverLaunchRequest, opts ...grpc.CallOption) (*ReceiverLaunchReply, error) {
	out := new(ReceiverLaunchReply)
	err := c.cc.Invoke(ctx, "/SyncAgentService/ReceiverLaunch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncAgentServiceClient) BackupCreate(ctx context.Context, in *BackupCreateRequest, opts ...grpc.CallOption) (*BackupCreateReply, error) {
	out := new(BackupCreateReply)
	err := c.cc.Invoke(ctx, "/SyncAgentService/BackupCreate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncAgentServiceClient) BackupRemove(ctx context.Context, in *BackupRemoveRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/SyncAgentService/BackupRemove", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncAgentServiceClient) BackupRestore(ctx context.Context, in *BackupRestoreRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/SyncAgentService/BackupRestore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncAgentServiceClient) BackupRestoreIncrementally(ctx context.Context, in *BackupRestoreIncrementallyRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/SyncAgentService/BackupRestoreIncrementally", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncAgentServiceClient) BackupGetStatus(ctx context.Context, in *BackupProgressRequest, opts ...grpc.CallOption) (*BackupProgressReply, error) {
	out := new(BackupProgressReply)
	err := c.cc.Invoke(ctx, "/SyncAgentService/BackupGetStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncAgentServiceClient) Reset(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/SyncAgentService/Reset", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncAgentServiceClient) RestoreStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RestoreStatusReply, error) {
	out := new(RestoreStatusReply)
	err := c.cc.Invoke(ctx, "/SyncAgentService/RestoreStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SyncAgentServiceServer is the server API for SyncAgentService service.
type SyncAgentServiceServer interface {
	FileRemove(context.Context, *FileRemoveRequest) (*Empty, error)
	FileRename(context.Context, *FileRenameRequest) (*Empty, error)
	FileCoalesce(context.Context, *FileCoalesceRequest) (*Empty, error)
	FileSend(context.Context, *FileSendRequest) (*Empty, error)
	ReceiverLaunch(context.Context, *ReceiverLaunchRequest) (*ReceiverLaunchReply, error)
	BackupCreate(context.Context, *BackupCreateRequest) (*BackupCreateReply, error)
	BackupRemove(context.Context, *BackupRemoveRequest) (*Empty, error)
	BackupRestore(context.Context, *BackupRestoreRequest) (*Empty, error)
	BackupRestoreIncrementally(context.Context, *BackupRestoreIncrementallyRequest) (*Empty, error)
	BackupGetStatus(context.Context, *BackupProgressRequest) (*BackupProgressReply, error)
	Reset(context.Context, *Empty) (*Empty, error)
	RestoreStatus(context.Context, *Empty) (*RestoreStatusReply, error)
}

// UnimplementedSyncAgentServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSyncAgentServiceServer struct {
}

func (*UnimplementedSyncAgentServiceServer) FileRemove(ctx context.Context, req *FileRemoveRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FileRemove not implemented")
}
func (*UnimplementedSyncAgentServiceServer) FileRename(ctx context.Context, req *FileRenameRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FileRename not implemented")
}
func (*UnimplementedSyncAgentServiceServer) FileCoalesce(ctx context.Context, req *FileCoalesceRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FileCoalesce not implemented")
}
func (*UnimplementedSyncAgentServiceServer) FileSend(ctx context.Context, req *FileSendRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FileSend not implemented")
}
func (*UnimplementedSyncAgentServiceServer) ReceiverLaunch(ctx context.Context, req *ReceiverLaunchRequest) (*ReceiverLaunchReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReceiverLaunch not implemented")
}
func (*UnimplementedSyncAgentServiceServer) BackupCreate(ctx context.Context, req *BackupCreateRequest) (*BackupCreateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BackupCreate not implemented")
}
func (*UnimplementedSyncAgentServiceServer) BackupRemove(ctx context.Context, req *BackupRemoveRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BackupRemove not implemented")
}
func (*UnimplementedSyncAgentServiceServer) BackupRestore(ctx context.Context, req *BackupRestoreRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BackupRestore not implemented")
}
func (*UnimplementedSyncAgentServiceServer) BackupRestoreIncrementally(ctx context.Context, req *BackupRestoreIncrementallyRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BackupRestoreIncrementally not implemented")
}
func (*UnimplementedSyncAgentServiceServer) BackupGetStatus(ctx context.Context, req *BackupProgressRequest) (*BackupProgressReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BackupGetStatus not implemented")
}
func (*UnimplementedSyncAgentServiceServer) Reset(ctx context.Context, req *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reset not implemented")
}
func (*UnimplementedSyncAgentServiceServer) RestoreStatus(ctx context.Context, req *Empty) (*RestoreStatusReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RestoreStatus not implemented")
}

func RegisterSyncAgentServiceServer(s *grpc.Server, srv SyncAgentServiceServer) {
	s.RegisterService(&_SyncAgentService_serviceDesc, srv)
}

func _SyncAgentService_FileRemove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileRemoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncAgentServiceServer).FileRemove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SyncAgentService/FileRemove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncAgentServiceServer).FileRemove(ctx, req.(*FileRemoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncAgentService_FileRename_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileRenameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncAgentServiceServer).FileRename(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SyncAgentService/FileRename",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncAgentServiceServer).FileRename(ctx, req.(*FileRenameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncAgentService_FileCoalesce_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileCoalesceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncAgentServiceServer).FileCoalesce(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SyncAgentService/FileCoalesce",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncAgentServiceServer).FileCoalesce(ctx, req.(*FileCoalesceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncAgentService_FileSend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileSendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncAgentServiceServer).FileSend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SyncAgentService/FileSend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncAgentServiceServer).FileSend(ctx, req.(*FileSendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncAgentService_ReceiverLaunch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReceiverLaunchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncAgentServiceServer).ReceiverLaunch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SyncAgentService/ReceiverLaunch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncAgentServiceServer).ReceiverLaunch(ctx, req.(*ReceiverLaunchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncAgentService_BackupCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BackupCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncAgentServiceServer).BackupCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SyncAgentService/BackupCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncAgentServiceServer).BackupCreate(ctx, req.(*BackupCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncAgentService_BackupRemove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BackupRemoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncAgentServiceServer).BackupRemove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SyncAgentService/BackupRemove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncAgentServiceServer).BackupRemove(ctx, req.(*BackupRemoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncAgentService_BackupRestore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BackupRestoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncAgentServiceServer).BackupRestore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SyncAgentService/BackupRestore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncAgentServiceServer).BackupRestore(ctx, req.(*BackupRestoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncAgentService_BackupRestoreIncrementally_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BackupRestoreIncrementallyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncAgentServiceServer).BackupRestoreIncrementally(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SyncAgentService/BackupRestoreIncrementally",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncAgentServiceServer).BackupRestoreIncrementally(ctx, req.(*BackupRestoreIncrementallyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncAgentService_BackupGetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BackupProgressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncAgentServiceServer).BackupGetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SyncAgentService/BackupGetStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncAgentServiceServer).BackupGetStatus(ctx, req.(*BackupProgressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncAgentService_Reset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncAgentServiceServer).Reset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SyncAgentService/Reset",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncAgentServiceServer).Reset(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncAgentService_RestoreStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncAgentServiceServer).RestoreStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SyncAgentService/RestoreStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncAgentServiceServer).RestoreStatus(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _SyncAgentService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "SyncAgentService",
	HandlerType: (*SyncAgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FileRemove",
			Handler:    _SyncAgentService_FileRemove_Handler,
		},
		{
			MethodName: "FileRename",
			Handler:    _SyncAgentService_FileRename_Handler,
		},
		{
			MethodName: "FileCoalesce",
			Handler:    _SyncAgentService_FileCoalesce_Handler,
		},
		{
			MethodName: "FileSend",
			Handler:    _SyncAgentService_FileSend_Handler,
		},
		{
			MethodName: "ReceiverLaunch",
			Handler:    _SyncAgentService_ReceiverLaunch_Handler,
		},
		{
			MethodName: "BackupCreate",
			Handler:    _SyncAgentService_BackupCreate_Handler,
		},
		{
			MethodName: "BackupRemove",
			Handler:    _SyncAgentService_BackupRemove_Handler,
		},
		{
			MethodName: "BackupRestore",
			Handler:    _SyncAgentService_BackupRestore_Handler,
		},
		{
			MethodName: "BackupRestoreIncrementally",
			Handler:    _SyncAgentService_BackupRestoreIncrementally_Handler,
		},
		{
			MethodName: "BackupGetStatus",
			Handler:    _SyncAgentService_BackupGetStatus_Handler,
		},
		{
			MethodName: "Reset",
			Handler:    _SyncAgentService_Reset_Handler,
		},
		{
			MethodName: "RestoreStatus",
			Handler:    _SyncAgentService_RestoreStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc.proto",
}
