// Code generated by protoc-gen-go. DO NOT EDIT.
// source: syncagent.proto

package ptypes

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FileRemoveRequest struct {
	FileName             string   `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileRemoveRequest) Reset()         { *m = FileRemoveRequest{} }
func (m *FileRemoveRequest) String() string { return proto.CompactTextString(m) }
func (*FileRemoveRequest) ProtoMessage()    {}
func (*FileRemoveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_68e10ca3dfff6283, []int{0}
}

func (m *FileRemoveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileRemoveRequest.Unmarshal(m, b)
}
func (m *FileRemoveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileRemoveRequest.Marshal(b, m, deterministic)
}
func (m *FileRemoveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileRemoveRequest.Merge(m, src)
}
func (m *FileRemoveRequest) XXX_Size() int {
	return xxx_messageInfo_FileRemoveRequest.Size(m)
}
func (m *FileRemoveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FileRemoveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FileRemoveRequest proto.InternalMessageInfo

func (m *FileRemoveRequest) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

type FileRenameRequest struct {
	OldFileName          string   `protobuf:"bytes,1,opt,name=old_file_name,json=oldFileName,proto3" json:"old_file_name,omitempty"`
	NewFileName          string   `protobuf:"bytes,2,opt,name=new_file_name,json=newFileName,proto3" json:"new_file_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileRenameRequest) Reset()         { *m = FileRenameRequest{} }
func (m *FileRenameRequest) String() string { return proto.CompactTextString(m) }
func (*FileRenameRequest) ProtoMessage()    {}
func (*FileRenameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_68e10ca3dfff6283, []int{1}
}

func (m *FileRenameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileRenameRequest.Unmarshal(m, b)
}
func (m *FileRenameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileRenameRequest.Marshal(b, m, deterministic)
}
func (m *FileRenameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileRenameRequest.Merge(m, src)
}
func (m *FileRenameRequest) XXX_Size() int {
	return xxx_messageInfo_FileRenameRequest.Size(m)
}
func (m *FileRenameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FileRenameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FileRenameRequest proto.InternalMessageInfo

func (m *FileRenameRequest) GetOldFileName() string {
	if m != nil {
		return m.OldFileName
	}
	return ""
}

func (m *FileRenameRequest) GetNewFileName() string {
	if m != nil {
		return m.NewFileName
	}
	return ""
}

type ReceiverLaunchRequest struct {
	ToFileName           string   `protobuf:"bytes,1,opt,name=to_file_name,json=toFileName,proto3" json:"to_file_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReceiverLaunchRequest) Reset()         { *m = ReceiverLaunchRequest{} }
func (m *ReceiverLaunchRequest) String() string { return proto.CompactTextString(m) }
func (*ReceiverLaunchRequest) ProtoMessage()    {}
func (*ReceiverLaunchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_68e10ca3dfff6283, []int{2}
}

func (m *ReceiverLaunchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiverLaunchRequest.Unmarshal(m, b)
}
func (m *ReceiverLaunchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiverLaunchRequest.Marshal(b, m, deterministic)
}
func (m *ReceiverLaunchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiverLaunchRequest.Merge(m, src)
}
func (m *ReceiverLaunchRequest) XXX_Size() int {
	return xxx_messageInfo_ReceiverLaunchRequest.Size(m)
}
func (m *ReceiverLaunchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiverLaunchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiverLaunchRequest proto.InternalMessageInfo

func (m *ReceiverLaunchRequest) GetToFileName() string {
	if m != nil {
		return m.ToFileName
	}
	return ""
}

type ReceiverLaunchResponse struct {
	Port                 int32    `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReceiverLaunchResponse) Reset()         { *m = ReceiverLaunchResponse{} }
func (m *ReceiverLaunchResponse) String() string { return proto.CompactTextString(m) }
func (*ReceiverLaunchResponse) ProtoMessage()    {}
func (*ReceiverLaunchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_68e10ca3dfff6283, []int{3}
}

func (m *ReceiverLaunchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiverLaunchResponse.Unmarshal(m, b)
}
func (m *ReceiverLaunchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiverLaunchResponse.Marshal(b, m, deterministic)
}
func (m *ReceiverLaunchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiverLaunchResponse.Merge(m, src)
}
func (m *ReceiverLaunchResponse) XXX_Size() int {
	return xxx_messageInfo_ReceiverLaunchResponse.Size(m)
}
func (m *ReceiverLaunchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiverLaunchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiverLaunchResponse proto.InternalMessageInfo

func (m *ReceiverLaunchResponse) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type FileSendRequest struct {
	FromFileName         string   `protobuf:"bytes,1,opt,name=from_file_name,json=fromFileName,proto3" json:"from_file_name,omitempty"`
	Host                 string   `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port                 int32    `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileSendRequest) Reset()         { *m = FileSendRequest{} }
func (m *FileSendRequest) String() string { return proto.CompactTextString(m) }
func (*FileSendRequest) ProtoMessage()    {}
func (*FileSendRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_68e10ca3dfff6283, []int{4}
}

func (m *FileSendRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileSendRequest.Unmarshal(m, b)
}
func (m *FileSendRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileSendRequest.Marshal(b, m, deterministic)
}
func (m *FileSendRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileSendRequest.Merge(m, src)
}
func (m *FileSendRequest) XXX_Size() int {
	return xxx_messageInfo_FileSendRequest.Size(m)
}
func (m *FileSendRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FileSendRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FileSendRequest proto.InternalMessageInfo

func (m *FileSendRequest) GetFromFileName() string {
	if m != nil {
		return m.FromFileName
	}
	return ""
}

func (m *FileSendRequest) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *FileSendRequest) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type FilesSyncRequest struct {
	FromAddress          string          `protobuf:"bytes,1,opt,name=from_address,json=fromAddress,proto3" json:"from_address,omitempty"`
	ToHost               string          `protobuf:"bytes,2,opt,name=to_host,json=toHost,proto3" json:"to_host,omitempty"`
	SyncFileInfoList     []*SyncFileInfo `protobuf:"bytes,3,rep,name=sync_file_info_list,json=syncFileInfoList,proto3" json:"sync_file_info_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *FilesSyncRequest) Reset()         { *m = FilesSyncRequest{} }
func (m *FilesSyncRequest) String() string { return proto.CompactTextString(m) }
func (*FilesSyncRequest) ProtoMessage()    {}
func (*FilesSyncRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_68e10ca3dfff6283, []int{5}
}

func (m *FilesSyncRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilesSyncRequest.Unmarshal(m, b)
}
func (m *FilesSyncRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilesSyncRequest.Marshal(b, m, deterministic)
}
func (m *FilesSyncRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilesSyncRequest.Merge(m, src)
}
func (m *FilesSyncRequest) XXX_Size() int {
	return xxx_messageInfo_FilesSyncRequest.Size(m)
}
func (m *FilesSyncRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FilesSyncRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FilesSyncRequest proto.InternalMessageInfo

func (m *FilesSyncRequest) GetFromAddress() string {
	if m != nil {
		return m.FromAddress
	}
	return ""
}

func (m *FilesSyncRequest) GetToHost() string {
	if m != nil {
		return m.ToHost
	}
	return ""
}

func (m *FilesSyncRequest) GetSyncFileInfoList() []*SyncFileInfo {
	if m != nil {
		return m.SyncFileInfoList
	}
	return nil
}

type BackupCreateRequest struct {
	SnapshotFileName     string            `protobuf:"bytes,1,opt,name=snapshot_file_name,json=snapshotFileName,proto3" json:"snapshot_file_name,omitempty"`
	BackupTarget         string            `protobuf:"bytes,2,opt,name=backup_target,json=backupTarget,proto3" json:"backup_target,omitempty"`
	VolumeName           string            `protobuf:"bytes,3,opt,name=volume_name,json=volumeName,proto3" json:"volume_name,omitempty"`
	Labels               []string          `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty"`
	Credential           map[string]string `protobuf:"bytes,5,rep,name=credential,proto3" json:"credential,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	BackingImageName     string            `protobuf:"bytes,6,opt,name=backing_image_name,json=backingImageName,proto3" json:"backing_image_name,omitempty"`
	BackingImageUrl      string            `protobuf:"bytes,7,opt,name=backing_image_url,json=backingImageUrl,proto3" json:"backing_image_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *BackupCreateRequest) Reset()         { *m = BackupCreateRequest{} }
func (m *BackupCreateRequest) String() string { return proto.CompactTextString(m) }
func (*BackupCreateRequest) ProtoMessage()    {}
func (*BackupCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_68e10ca3dfff6283, []int{6}
}

func (m *BackupCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackupCreateRequest.Unmarshal(m, b)
}
func (m *BackupCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackupCreateRequest.Marshal(b, m, deterministic)
}
func (m *BackupCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackupCreateRequest.Merge(m, src)
}
func (m *BackupCreateRequest) XXX_Size() int {
	return xxx_messageInfo_BackupCreateRequest.Size(m)
}
func (m *BackupCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BackupCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BackupCreateRequest proto.InternalMessageInfo

func (m *BackupCreateRequest) GetSnapshotFileName() string {
	if m != nil {
		return m.SnapshotFileName
	}
	return ""
}

func (m *BackupCreateRequest) GetBackupTarget() string {
	if m != nil {
		return m.BackupTarget
	}
	return ""
}

func (m *BackupCreateRequest) GetVolumeName() string {
	if m != nil {
		return m.VolumeName
	}
	return ""
}

func (m *BackupCreateRequest) GetLabels() []string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *BackupCreateRequest) GetCredential() map[string]string {
	if m != nil {
		return m.Credential
	}
	return nil
}

func (m *BackupCreateRequest) GetBackingImageName() string {
	if m != nil {
		return m.BackingImageName
	}
	return ""
}

func (m *BackupCreateRequest) GetBackingImageUrl() string {
	if m != nil {
		return m.BackingImageUrl
	}
	return ""
}

type BackupCreateResponse struct {
	Backup               string   `protobuf:"bytes,1,opt,name=backup,proto3" json:"backup,omitempty"`
	IsIncremental        bool     `protobuf:"varint,2,opt,name=is_incremental,json=isIncremental,proto3" json:"is_incremental,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BackupCreateResponse) Reset()         { *m = BackupCreateResponse{} }
func (m *BackupCreateResponse) String() string { return proto.CompactTextString(m) }
func (*BackupCreateResponse) ProtoMessage()    {}
func (*BackupCreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_68e10ca3dfff6283, []int{7}
}

func (m *BackupCreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackupCreateResponse.Unmarshal(m, b)
}
func (m *BackupCreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackupCreateResponse.Marshal(b, m, deterministic)
}
func (m *BackupCreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackupCreateResponse.Merge(m, src)
}
func (m *BackupCreateResponse) XXX_Size() int {
	return xxx_messageInfo_BackupCreateResponse.Size(m)
}
func (m *BackupCreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BackupCreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BackupCreateResponse proto.InternalMessageInfo

func (m *BackupCreateResponse) GetBackup() string {
	if m != nil {
		return m.Backup
	}
	return ""
}

func (m *BackupCreateResponse) GetIsIncremental() bool {
	if m != nil {
		return m.IsIncremental
	}
	return false
}

type BackupRemoveRequest struct {
	Backup               string   `protobuf:"bytes,1,opt,name=backup,proto3" json:"backup,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BackupRemoveRequest) Reset()         { *m = BackupRemoveRequest{} }
func (m *BackupRemoveRequest) String() string { return proto.CompactTextString(m) }
func (*BackupRemoveRequest) ProtoMessage()    {}
func (*BackupRemoveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_68e10ca3dfff6283, []int{8}
}

func (m *BackupRemoveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackupRemoveRequest.Unmarshal(m, b)
}
func (m *BackupRemoveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackupRemoveRequest.Marshal(b, m, deterministic)
}
func (m *BackupRemoveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackupRemoveRequest.Merge(m, src)
}
func (m *BackupRemoveRequest) XXX_Size() int {
	return xxx_messageInfo_BackupRemoveRequest.Size(m)
}
func (m *BackupRemoveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BackupRemoveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BackupRemoveRequest proto.InternalMessageInfo

func (m *BackupRemoveRequest) GetBackup() string {
	if m != nil {
		return m.Backup
	}
	return ""
}

type BackupStatusRequest struct {
	Backup               string   `protobuf:"bytes,1,opt,name=backup,proto3" json:"backup,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BackupStatusRequest) Reset()         { *m = BackupStatusRequest{} }
func (m *BackupStatusRequest) String() string { return proto.CompactTextString(m) }
func (*BackupStatusRequest) ProtoMessage()    {}
func (*BackupStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_68e10ca3dfff6283, []int{9}
}

func (m *BackupStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackupStatusRequest.Unmarshal(m, b)
}
func (m *BackupStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackupStatusRequest.Marshal(b, m, deterministic)
}
func (m *BackupStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackupStatusRequest.Merge(m, src)
}
func (m *BackupStatusRequest) XXX_Size() int {
	return xxx_messageInfo_BackupStatusRequest.Size(m)
}
func (m *BackupStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BackupStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BackupStatusRequest proto.InternalMessageInfo

func (m *BackupStatusRequest) GetBackup() string {
	if m != nil {
		return m.Backup
	}
	return ""
}

type BackupStatusResponse struct {
	Progress             int32    `protobuf:"varint,1,opt,name=progress,proto3" json:"progress,omitempty"`
	BackupUrl            string   `protobuf:"bytes,2,opt,name=backup_url,json=backupUrl,proto3" json:"backup_url,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	SnapshotName         string   `protobuf:"bytes,4,opt,name=snapshot_name,json=snapshotName,proto3" json:"snapshot_name,omitempty"`
	State                string   `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BackupStatusResponse) Reset()         { *m = BackupStatusResponse{} }
func (m *BackupStatusResponse) String() string { return proto.CompactTextString(m) }
func (*BackupStatusResponse) ProtoMessage()    {}
func (*BackupStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_68e10ca3dfff6283, []int{10}
}

func (m *BackupStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackupStatusResponse.Unmarshal(m, b)
}
func (m *BackupStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackupStatusResponse.Marshal(b, m, deterministic)
}
func (m *BackupStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackupStatusResponse.Merge(m, src)
}
func (m *BackupStatusResponse) XXX_Size() int {
	return xxx_messageInfo_BackupStatusResponse.Size(m)
}
func (m *BackupStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BackupStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BackupStatusResponse proto.InternalMessageInfo

func (m *BackupStatusResponse) GetProgress() int32 {
	if m != nil {
		return m.Progress
	}
	return 0
}

func (m *BackupStatusResponse) GetBackupUrl() string {
	if m != nil {
		return m.BackupUrl
	}
	return ""
}

func (m *BackupStatusResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *BackupStatusResponse) GetSnapshotName() string {
	if m != nil {
		return m.SnapshotName
	}
	return ""
}

func (m *BackupStatusResponse) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

type BackupRestoreRequest struct {
	Backup               string            `protobuf:"bytes,1,opt,name=backup,proto3" json:"backup,omitempty"`
	SnapshotDiskName     string            `protobuf:"bytes,2,opt,name=snapshot_disk_name,json=snapshotDiskName,proto3" json:"snapshot_disk_name,omitempty"`
	Credential           map[string]string `protobuf:"bytes,3,rep,name=credential,proto3" json:"credential,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *BackupRestoreRequest) Reset()         { *m = BackupRestoreRequest{} }
func (m *BackupRestoreRequest) String() string { return proto.CompactTextString(m) }
func (*BackupRestoreRequest) ProtoMessage()    {}
func (*BackupRestoreRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_68e10ca3dfff6283, []int{11}
}

func (m *BackupRestoreRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackupRestoreRequest.Unmarshal(m, b)
}
func (m *BackupRestoreRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackupRestoreRequest.Marshal(b, m, deterministic)
}
func (m *BackupRestoreRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackupRestoreRequest.Merge(m, src)
}
func (m *BackupRestoreRequest) XXX_Size() int {
	return xxx_messageInfo_BackupRestoreRequest.Size(m)
}
func (m *BackupRestoreRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BackupRestoreRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BackupRestoreRequest proto.InternalMessageInfo

func (m *BackupRestoreRequest) GetBackup() string {
	if m != nil {
		return m.Backup
	}
	return ""
}

func (m *BackupRestoreRequest) GetSnapshotDiskName() string {
	if m != nil {
		return m.SnapshotDiskName
	}
	return ""
}

func (m *BackupRestoreRequest) GetCredential() map[string]string {
	if m != nil {
		return m.Credential
	}
	return nil
}

type BackupRestoreIncrementallyRequest struct {
	Backup                 string            `protobuf:"bytes,1,opt,name=backup,proto3" json:"backup,omitempty"`
	DeltaFileName          string            `protobuf:"bytes,2,opt,name=delta_file_name,json=deltaFileName,proto3" json:"delta_file_name,omitempty"`
	LastRestoredBackupName string            `protobuf:"bytes,3,opt,name=last_restored_backup_name,json=lastRestoredBackupName,proto3" json:"last_restored_backup_name,omitempty"`
	SnapshotDiskName       string            `protobuf:"bytes,4,opt,name=snapshot_disk_name,json=snapshotDiskName,proto3" json:"snapshot_disk_name,omitempty"`
	Credential             map[string]string `protobuf:"bytes,5,rep,name=credential,proto3" json:"credential,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral   struct{}          `json:"-"`
	XXX_unrecognized       []byte            `json:"-"`
	XXX_sizecache          int32             `json:"-"`
}

func (m *BackupRestoreIncrementallyRequest) Reset()         { *m = BackupRestoreIncrementallyRequest{} }
func (m *BackupRestoreIncrementallyRequest) String() string { return proto.CompactTextString(m) }
func (*BackupRestoreIncrementallyRequest) ProtoMessage()    {}
func (*BackupRestoreIncrementallyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_68e10ca3dfff6283, []int{12}
}

func (m *BackupRestoreIncrementallyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackupRestoreIncrementallyRequest.Unmarshal(m, b)
}
func (m *BackupRestoreIncrementallyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackupRestoreIncrementallyRequest.Marshal(b, m, deterministic)
}
func (m *BackupRestoreIncrementallyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackupRestoreIncrementallyRequest.Merge(m, src)
}
func (m *BackupRestoreIncrementallyRequest) XXX_Size() int {
	return xxx_messageInfo_BackupRestoreIncrementallyRequest.Size(m)
}
func (m *BackupRestoreIncrementallyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BackupRestoreIncrementallyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BackupRestoreIncrementallyRequest proto.InternalMessageInfo

func (m *BackupRestoreIncrementallyRequest) GetBackup() string {
	if m != nil {
		return m.Backup
	}
	return ""
}

func (m *BackupRestoreIncrementallyRequest) GetDeltaFileName() string {
	if m != nil {
		return m.DeltaFileName
	}
	return ""
}

func (m *BackupRestoreIncrementallyRequest) GetLastRestoredBackupName() string {
	if m != nil {
		return m.LastRestoredBackupName
	}
	return ""
}

func (m *BackupRestoreIncrementallyRequest) GetSnapshotDiskName() string {
	if m != nil {
		return m.SnapshotDiskName
	}
	return ""
}

func (m *BackupRestoreIncrementallyRequest) GetCredential() map[string]string {
	if m != nil {
		return m.Credential
	}
	return nil
}

type RestoreStatusResponse struct {
	IsRestoring            bool     `protobuf:"varint,1,opt,name=is_restoring,json=isRestoring,proto3" json:"is_restoring,omitempty"`
	LastRestored           string   `protobuf:"bytes,2,opt,name=last_restored,json=lastRestored,proto3" json:"last_restored,omitempty"`
	Progress               int32    `protobuf:"varint,3,opt,name=progress,proto3" json:"progress,omitempty"`
	Error                  string   `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	DestFileName           string   `protobuf:"bytes,5,opt,name=dest_file_name,json=destFileName,proto3" json:"dest_file_name,omitempty"`
	State                  string   `protobuf:"bytes,6,opt,name=state,proto3" json:"state,omitempty"`
	BackupUrl              string   `protobuf:"bytes,7,opt,name=backup_url,json=backupUrl,proto3" json:"backup_url,omitempty"`
	CurrentRestoringBackup string   `protobuf:"bytes,8,opt,name=current_restoring_backup,json=currentRestoringBackup,proto3" json:"current_restoring_backup,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *RestoreStatusResponse) Reset()         { *m = RestoreStatusResponse{} }
func (m *RestoreStatusResponse) String() string { return proto.CompactTextString(m) }
func (*RestoreStatusResponse) ProtoMessage()    {}
func (*RestoreStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_68e10ca3dfff6283, []int{13}
}

func (m *RestoreStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestoreStatusResponse.Unmarshal(m, b)
}
func (m *RestoreStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestoreStatusResponse.Marshal(b, m, deterministic)
}
func (m *RestoreStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestoreStatusResponse.Merge(m, src)
}
func (m *RestoreStatusResponse) XXX_Size() int {
	return xxx_messageInfo_RestoreStatusResponse.Size(m)
}
func (m *RestoreStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RestoreStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RestoreStatusResponse proto.InternalMessageInfo

func (m *RestoreStatusResponse) GetIsRestoring() bool {
	if m != nil {
		return m.IsRestoring
	}
	return false
}

func (m *RestoreStatusResponse) GetLastRestored() string {
	if m != nil {
		return m.LastRestored
	}
	return ""
}

func (m *RestoreStatusResponse) GetProgress() int32 {
	if m != nil {
		return m.Progress
	}
	return 0
}

func (m *RestoreStatusResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *RestoreStatusResponse) GetDestFileName() string {
	if m != nil {
		return m.DestFileName
	}
	return ""
}

func (m *RestoreStatusResponse) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *RestoreStatusResponse) GetBackupUrl() string {
	if m != nil {
		return m.BackupUrl
	}
	return ""
}

func (m *RestoreStatusResponse) GetCurrentRestoringBackup() string {
	if m != nil {
		return m.CurrentRestoringBackup
	}
	return ""
}

type SnapshotPurgeStatusResponse struct {
	IsPurging            bool     `protobuf:"varint,1,opt,name=is_purging,json=isPurging,proto3" json:"is_purging,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Progress             int32    `protobuf:"varint,3,opt,name=progress,proto3" json:"progress,omitempty"`
	State                string   `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SnapshotPurgeStatusResponse) Reset()         { *m = SnapshotPurgeStatusResponse{} }
func (m *SnapshotPurgeStatusResponse) String() string { return proto.CompactTextString(m) }
func (*SnapshotPurgeStatusResponse) ProtoMessage()    {}
func (*SnapshotPurgeStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_68e10ca3dfff6283, []int{14}
}

func (m *SnapshotPurgeStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SnapshotPurgeStatusResponse.Unmarshal(m, b)
}
func (m *SnapshotPurgeStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SnapshotPurgeStatusResponse.Marshal(b, m, deterministic)
}
func (m *SnapshotPurgeStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SnapshotPurgeStatusResponse.Merge(m, src)
}
func (m *SnapshotPurgeStatusResponse) XXX_Size() int {
	return xxx_messageInfo_SnapshotPurgeStatusResponse.Size(m)
}
func (m *SnapshotPurgeStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SnapshotPurgeStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SnapshotPurgeStatusResponse proto.InternalMessageInfo

func (m *SnapshotPurgeStatusResponse) GetIsPurging() bool {
	if m != nil {
		return m.IsPurging
	}
	return false
}

func (m *SnapshotPurgeStatusResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *SnapshotPurgeStatusResponse) GetProgress() int32 {
	if m != nil {
		return m.Progress
	}
	return 0
}

func (m *SnapshotPurgeStatusResponse) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

type ReplicaRebuildStatusResponse struct {
	IsRebuilding         bool     `protobuf:"varint,1,opt,name=is_rebuilding,json=isRebuilding,proto3" json:"is_rebuilding,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Progress             int32    `protobuf:"varint,3,opt,name=progress,proto3" json:"progress,omitempty"`
	State                string   `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	FromReplicaAddress   string   `protobuf:"bytes,5,opt,name=from_replica_address,json=fromReplicaAddress,proto3" json:"from_replica_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplicaRebuildStatusResponse) Reset()         { *m = ReplicaRebuildStatusResponse{} }
func (m *ReplicaRebuildStatusResponse) String() string { return proto.CompactTextString(m) }
func (*ReplicaRebuildStatusResponse) ProtoMessage()    {}
func (*ReplicaRebuildStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_68e10ca3dfff6283, []int{15}
}

func (m *ReplicaRebuildStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplicaRebuildStatusResponse.Unmarshal(m, b)
}
func (m *ReplicaRebuildStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplicaRebuildStatusResponse.Marshal(b, m, deterministic)
}
func (m *ReplicaRebuildStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplicaRebuildStatusResponse.Merge(m, src)
}
func (m *ReplicaRebuildStatusResponse) XXX_Size() int {
	return xxx_messageInfo_ReplicaRebuildStatusResponse.Size(m)
}
func (m *ReplicaRebuildStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplicaRebuildStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReplicaRebuildStatusResponse proto.InternalMessageInfo

func (m *ReplicaRebuildStatusResponse) GetIsRebuilding() bool {
	if m != nil {
		return m.IsRebuilding
	}
	return false
}

func (m *ReplicaRebuildStatusResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *ReplicaRebuildStatusResponse) GetProgress() int32 {
	if m != nil {
		return m.Progress
	}
	return 0
}

func (m *ReplicaRebuildStatusResponse) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *ReplicaRebuildStatusResponse) GetFromReplicaAddress() string {
	if m != nil {
		return m.FromReplicaAddress
	}
	return ""
}

func init() {
	proto.RegisterType((*FileRemoveRequest)(nil), "ptypes.FileRemoveRequest")
	proto.RegisterType((*FileRenameRequest)(nil), "ptypes.FileRenameRequest")
	proto.RegisterType((*ReceiverLaunchRequest)(nil), "ptypes.ReceiverLaunchRequest")
	proto.RegisterType((*ReceiverLaunchResponse)(nil), "ptypes.ReceiverLaunchResponse")
	proto.RegisterType((*FileSendRequest)(nil), "ptypes.FileSendRequest")
	proto.RegisterType((*FilesSyncRequest)(nil), "ptypes.FilesSyncRequest")
	proto.RegisterType((*BackupCreateRequest)(nil), "ptypes.BackupCreateRequest")
	proto.RegisterMapType((map[string]string)(nil), "ptypes.BackupCreateRequest.CredentialEntry")
	proto.RegisterType((*BackupCreateResponse)(nil), "ptypes.BackupCreateResponse")
	proto.RegisterType((*BackupRemoveRequest)(nil), "ptypes.BackupRemoveRequest")
	proto.RegisterType((*BackupStatusRequest)(nil), "ptypes.BackupStatusRequest")
	proto.RegisterType((*BackupStatusResponse)(nil), "ptypes.BackupStatusResponse")
	proto.RegisterType((*BackupRestoreRequest)(nil), "ptypes.BackupRestoreRequest")
	proto.RegisterMapType((map[string]string)(nil), "ptypes.BackupRestoreRequest.CredentialEntry")
	proto.RegisterType((*BackupRestoreIncrementallyRequest)(nil), "ptypes.BackupRestoreIncrementallyRequest")
	proto.RegisterMapType((map[string]string)(nil), "ptypes.BackupRestoreIncrementallyRequest.CredentialEntry")
	proto.RegisterType((*RestoreStatusResponse)(nil), "ptypes.RestoreStatusResponse")
	proto.RegisterType((*SnapshotPurgeStatusResponse)(nil), "ptypes.SnapshotPurgeStatusResponse")
	proto.RegisterType((*ReplicaRebuildStatusResponse)(nil), "ptypes.ReplicaRebuildStatusResponse")
}

func init() { proto.RegisterFile("syncagent.proto", fileDescriptor_68e10ca3dfff6283) }

var fileDescriptor_68e10ca3dfff6283 = []byte{
	// 1173 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xdd, 0x4e, 0x1c, 0xb7,
	0x17, 0x67, 0xd9, 0x0f, 0x96, 0xc3, 0x2e, 0x10, 0xb3, 0x7f, 0xb2, 0x59, 0xe0, 0x5f, 0x18, 0x68,
	0x15, 0xb5, 0x74, 0x13, 0xa5, 0x37, 0xa1, 0x52, 0x54, 0x51, 0x4a, 0x1a, 0x14, 0x54, 0xa5, 0x43,
	0xa8, 0x54, 0xf5, 0x62, 0x34, 0xcc, 0x98, 0xc5, 0x62, 0x76, 0x3c, 0xb5, 0x3d, 0x44, 0x7b, 0x5f,
	0xa9, 0x17, 0xbd, 0xec, 0x1b, 0xf4, 0xa2, 0x6f, 0xd1, 0xd7, 0xa9, 0xd4, 0xb7, 0xa8, 0x6c, 0x8f,
	0x67, 0x3d, 0xb3, 0x1f, 0x54, 0xfd, 0xb8, 0xb3, 0x8f, 0xcf, 0xf9, 0x9d, 0xef, 0xe3, 0x03, 0x6b,
	0x7c, 0x14, 0x07, 0xfe, 0x00, 0xc7, 0xa2, 0x9f, 0x30, 0x2a, 0x28, 0x6a, 0x24, 0x62, 0x94, 0x60,
	0xde, 0xdb, 0x1a, 0x50, 0x3a, 0x88, 0xf0, 0x13, 0x45, 0xbd, 0x4a, 0xaf, 0x9f, 0xe0, 0x61, 0x22,
	0x46, 0x9a, 0xa9, 0xd7, 0x0a, 0xe8, 0x70, 0x48, 0x63, 0x7d, 0x73, 0x9e, 0xc2, 0x83, 0x97, 0x24,
	0xc2, 0x2e, 0x1e, 0xd2, 0x3b, 0xec, 0xe2, 0xef, 0x53, 0xcc, 0x05, 0xda, 0x82, 0xe5, 0x6b, 0x12,
	0x61, 0x2f, 0xf6, 0x87, 0xb8, 0x5b, 0xd9, 0xad, 0x3c, 0x5e, 0x76, 0x9b, 0x92, 0xf0, 0x95, 0x3f,
	0xc4, 0xce, 0x77, 0x46, 0x42, 0xbe, 0x1a, 0x09, 0x07, 0xda, 0x34, 0x0a, 0xbd, 0xb2, 0xd4, 0x0a,
	0x8d, 0xc2, 0x97, 0x99, 0xa0, 0xe4, 0x89, 0xf1, 0x3b, 0x8b, 0x67, 0x51, 0xf3, 0xc4, 0xf8, 0x9d,
	0xe1, 0x71, 0x8e, 0xe0, 0x7f, 0x2e, 0x0e, 0x30, 0xb9, 0xc3, 0xec, 0xdc, 0x4f, 0xe3, 0xe0, 0xc6,
	0x28, 0xd8, 0x85, 0x96, 0xa0, 0x13, 0xf8, 0x20, 0x68, 0x2e, 0x7a, 0x08, 0x9b, 0x65, 0x51, 0x9e,
	0xd0, 0x98, 0x63, 0x84, 0xa0, 0x96, 0x50, 0x26, 0x94, 0x4c, 0xdd, 0x55, 0x67, 0xc7, 0x83, 0x35,
	0x29, 0x79, 0x81, 0xe3, 0xd0, 0xa8, 0x38, 0x80, 0xd5, 0x6b, 0x46, 0x87, 0x13, 0x4a, 0x5a, 0x92,
	0x9a, 0x7b, 0x81, 0xa0, 0x76, 0x43, 0xb9, 0xc8, 0x8c, 0x57, 0xe7, 0x5c, 0x41, 0xd5, 0x52, 0xf0,
	0x73, 0x05, 0xd6, 0xa5, 0x10, 0xbf, 0x18, 0xc5, 0x81, 0x51, 0xb1, 0x07, 0x0a, 0xcc, 0xf3, 0xc3,
	0x90, 0x61, 0xce, 0x4d, 0x94, 0x24, 0xed, 0x58, 0x93, 0xd0, 0x43, 0x58, 0x12, 0xd4, 0xb3, 0x54,
	0x34, 0x04, 0x7d, 0x25, 0x95, 0x9c, 0xc0, 0x86, 0xcc, 0xb7, 0x36, 0x8f, 0xc4, 0xd7, 0xd4, 0x8b,
	0x08, 0x97, 0x3a, 0xab, 0x8f, 0x57, 0x9e, 0x75, 0xfa, 0x3a, 0xf5, 0x7d, 0xa9, 0x4d, 0xaa, 0x3d,
	0x8b, 0xaf, 0xa9, 0xbb, 0xce, 0xad, 0xdb, 0x39, 0xe1, 0xc2, 0xf9, 0xb1, 0x0a, 0x1b, 0x9f, 0xfb,
	0xc1, 0x6d, 0x9a, 0x9c, 0x30, 0xec, 0x8b, 0x3c, 0x7f, 0x87, 0x80, 0x78, 0xec, 0x27, 0xfc, 0x86,
	0x8a, 0x09, 0xff, 0xd7, 0xcd, 0x4b, 0x1e, 0x83, 0x7d, 0x68, 0x5f, 0x29, 0x10, 0x4f, 0xf8, 0x6c,
	0x80, 0x8d, 0xa5, 0x2d, 0x4d, 0x7c, 0xab, 0x68, 0xe8, 0x3d, 0x58, 0xb9, 0xa3, 0x51, 0x3a, 0xcc,
	0xb0, 0xaa, 0x3a, 0x61, 0x9a, 0xa4, 0x50, 0x36, 0xa1, 0x11, 0xf9, 0x57, 0x38, 0xe2, 0xdd, 0xda,
	0x6e, 0x55, 0x3a, 0xaa, 0x6f, 0xe8, 0x35, 0x40, 0xc0, 0x70, 0x88, 0x63, 0x41, 0xfc, 0xa8, 0x5b,
	0x57, 0xfe, 0x7d, 0x64, 0xfc, 0x9b, 0x62, 0x7c, 0xff, 0x24, 0xe7, 0x3e, 0x8d, 0x05, 0x1b, 0xb9,
	0x96, 0xb8, 0x74, 0x4c, 0x5a, 0x45, 0xe2, 0x81, 0x47, 0x86, 0xfe, 0x20, 0x33, 0xa6, 0xa1, 0x1d,
	0xcb, 0x5e, 0xce, 0xe4, 0x83, 0x32, 0xe9, 0x43, 0x78, 0x50, 0xe4, 0x4e, 0x59, 0xd4, 0x5d, 0x52,
	0xcc, 0x6b, 0x36, 0xf3, 0x25, 0x8b, 0x7a, 0x2f, 0x60, 0xad, 0xa4, 0x18, 0xad, 0x43, 0xf5, 0x16,
	0x8f, 0xb2, 0xb0, 0xc9, 0x23, 0xea, 0x40, 0xfd, 0xce, 0x8f, 0x52, 0x53, 0xeb, 0xfa, 0xf2, 0xe9,
	0xe2, 0xf3, 0x8a, 0x73, 0x09, 0x9d, 0xa2, 0x2f, 0x59, 0xb1, 0x6e, 0x42, 0x43, 0x87, 0x31, 0x83,
	0xc9, 0x6e, 0xe8, 0x7d, 0x58, 0x25, 0xdc, 0x23, 0x71, 0xc0, 0xf0, 0x10, 0xc7, 0xc2, 0x8f, 0x14,
	0x64, 0xd3, 0x6d, 0x13, 0x7e, 0x36, 0x26, 0x3a, 0x1f, 0x9b, 0xfc, 0x16, 0x3b, 0x7a, 0x06, 0xea,
	0x98, 0xfd, 0x42, 0xf8, 0x22, 0xe5, 0xf7, 0xb1, 0xff, 0x52, 0x31, 0x56, 0x1b, 0xfe, 0xcc, 0xea,
	0x1e, 0x34, 0x13, 0x46, 0x07, 0x79, 0x51, 0xd7, 0xdd, 0xfc, 0x8e, 0x76, 0x00, 0xb2, 0x6a, 0x91,
	0xd1, 0xd4, 0x81, 0x58, 0xd6, 0x94, 0x4b, 0x16, 0xc9, 0x10, 0x61, 0xc6, 0x28, 0xcb, 0x2a, 0x44,
	0x5f, 0x64, 0x89, 0xe5, 0x05, 0xa9, 0x52, 0x56, 0xd3, 0x25, 0x66, 0x88, 0x2a, 0x5d, 0x1d, 0xa8,
	0x73, 0xe1, 0x0b, 0xdc, 0xad, 0x6b, 0x51, 0x75, 0x71, 0xfe, 0xc8, 0x8d, 0x74, 0x31, 0x17, 0x94,
	0xdd, 0x17, 0x84, 0x42, 0xf1, 0x87, 0x84, 0xdf, 0xda, 0xd3, 0x29, 0x2f, 0xfe, 0x2f, 0x08, 0xbf,
	0x55, 0x4a, 0xcf, 0x0b, 0xe5, 0xa9, 0xdb, 0xef, 0xb0, 0x58, 0x9e, 0x45, 0xbd, 0xf3, 0xea, 0xf3,
	0x9f, 0x56, 0xd1, 0xef, 0x8b, 0xb0, 0x57, 0xd0, 0x69, 0xd5, 0x42, 0x34, 0xba, 0xcf, 0xf1, 0x0f,
	0x60, 0x2d, 0xc4, 0x91, 0xf0, 0x27, 0x66, 0x72, 0x5b, 0x91, 0xf3, 0x7e, 0x3f, 0x82, 0x47, 0x91,
	0xcf, 0x85, 0xc7, 0xb4, 0x8e, 0xd0, 0xcb, 0xf2, 0x69, 0x35, 0xf6, 0xa6, 0x64, 0xc8, 0x6c, 0x08,
	0xb5, 0x45, 0x4a, 0x74, 0x7a, 0x6c, 0x6b, 0x33, 0x62, 0xfb, 0xed, 0x94, 0xd6, 0x3f, 0x9a, 0x1a,
	0xdb, 0x69, 0x7e, 0xfe, 0x97, 0x81, 0xfe, 0x75, 0x51, 0xfe, 0x4c, 0x4a, 0x75, 0xa9, 0xf4, 0xf7,
	0xa0, 0x45, 0x78, 0x16, 0x1a, 0x12, 0x0f, 0x14, 0x5c, 0xd3, 0x5d, 0x21, 0xdc, 0x35, 0x24, 0x59,
	0xcc, 0x85, 0xf8, 0x99, 0x79, 0x69, 0xc7, 0xac, 0xd0, 0x42, 0xd5, 0x52, 0x0b, 0xe5, 0x3d, 0x52,
	0xb3, 0x7b, 0xe4, 0x00, 0x56, 0x43, 0xcc, 0xed, 0x81, 0xad, 0xfb, 0xa0, 0x25, 0xa9, 0x79, 0xf2,
	0xf2, 0x26, 0x69, 0x58, 0x4d, 0x52, 0x6a, 0xca, 0xa5, 0x72, 0x53, 0x3e, 0x87, 0x6e, 0x90, 0x32,
	0x86, 0x63, 0x31, 0xf6, 0x2c, 0xcb, 0x7a, 0xb7, 0xa9, 0x13, 0x9e, 0xbd, 0xe7, 0x5e, 0xea, 0xf4,
	0x38, 0x3f, 0x54, 0x60, 0xeb, 0x22, 0xcb, 0xeb, 0x9b, 0x94, 0x0d, 0xca, 0xe1, 0xda, 0x01, 0x20,
	0xdc, 0x4b, 0x52, 0x36, 0x18, 0x07, 0x6b, 0x99, 0xf0, 0x37, 0x9a, 0x30, 0xf6, 0x74, 0xd1, 0xf6,
	0xf4, 0x9e, 0xd8, 0x68, 0xff, 0x6a, 0xf6, 0x10, 0xf8, 0xad, 0x02, 0xdb, 0x2e, 0x4e, 0x22, 0x12,
	0xf8, 0x2e, 0xbe, 0x4a, 0x49, 0x14, 0x96, 0xec, 0xd8, 0x87, 0xb6, 0x4a, 0x9b, 0x7a, 0x1b, 0x9b,
	0xd2, 0x92, 0x79, 0x33, 0xb4, 0x7f, 0xcb, 0x1a, 0xf4, 0x14, 0x3a, 0xea, 0xdf, 0x67, 0xda, 0xa2,
	0xfc, 0xff, 0xd7, 0xf9, 0x42, 0xf2, 0x2d, 0x33, 0x36, 0x5b, 0x03, 0x9e, 0xfd, 0xd4, 0x84, 0x75,
	0xf9, 0x97, 0x1f, 0xcb, 0xf5, 0xee, 0x02, 0xb3, 0x3b, 0x12, 0x60, 0x74, 0x0c, 0x30, 0x5e, 0xd6,
	0xd0, 0x23, 0xd3, 0x18, 0x13, 0x0b, 0x5c, 0x6f, 0xb3, 0xaf, 0x37, 0xc0, 0xbe, 0xd9, 0x00, 0xfb,
	0xa7, 0x72, 0x03, 0x74, 0x16, 0xc6, 0x10, 0xb2, 0x5e, 0xca, 0x10, 0xd6, 0x46, 0x37, 0x07, 0xe2,
	0x05, 0x34, 0xcd, 0xea, 0x84, 0x1e, 0xda, 0x00, 0xd6, 0x32, 0x35, 0x47, 0xfc, 0x33, 0x58, 0xce,
	0xf7, 0x22, 0xd4, 0xb5, 0xe5, 0xed, 0x55, 0x69, 0x0e, 0xc0, 0xd7, 0xb0, 0x5a, 0x5c, 0xf4, 0xd0,
	0x8e, 0x41, 0x99, 0xba, 0x3b, 0xf6, 0xfe, 0x3f, 0xeb, 0x59, 0x97, 0x82, 0xb3, 0x80, 0x5e, 0x43,
	0xcb, 0xfe, 0x8c, 0xd1, 0xd6, 0x9c, 0x75, 0xa3, 0xb7, 0x3d, 0xfd, 0x31, 0x07, 0x3b, 0x35, 0x60,
	0x59, 0x9e, 0xb6, 0xca, 0x03, 0xec, 0xaf, 0x65, 0xea, 0x4b, 0x68, 0x17, 0x26, 0x1e, 0xda, 0x9e,
	0xf7, 0xc9, 0xcc, 0x01, 0xca, 0x9d, 0xd3, 0x1d, 0x50, 0xb6, 0xa7, 0xf0, 0xf3, 0x97, 0x9d, 0x2b,
	0x36, 0x8d, 0xb3, 0x80, 0x8e, 0xa0, 0xee, 0x62, 0x8e, 0x05, 0x9a, 0xa1, 0x6f, 0x8e, 0x1d, 0xaf,
	0xa0, 0x5d, 0x98, 0xa0, 0x33, 0x21, 0xac, 0x74, 0x4e, 0x19, 0xb8, 0xaa, 0x88, 0xdb, 0x85, 0x11,
	0xf3, 0x37, 0x8c, 0x79, 0x0b, 0x1b, 0x53, 0xa6, 0xd4, 0x4c, 0xa0, 0xfd, 0x7c, 0xbf, 0x9e, 0x3d,
	0xda, 0x9c, 0x05, 0xf4, 0x0d, 0x74, 0xa6, 0x0d, 0x9d, 0x99, 0xb0, 0x07, 0x63, 0x4f, 0x67, 0x8f,
	0x2a, 0x67, 0xe1, 0xaa, 0xa1, 0xe4, 0x3e, 0xf9, 0x33, 0x00, 0x00, 0xff, 0xff, 0x20, 0xf5, 0x28,
	0x91, 0xf2, 0x0d, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SyncAgentServiceClient is the client API for SyncAgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SyncAgentServiceClient interface {
	FileRemove(ctx context.Context, in *FileRemoveRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	FileRename(ctx context.Context, in *FileRenameRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	FileSend(ctx context.Context, in *FileSendRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	FilesSync(ctx context.Context, in *FilesSyncRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	ReceiverLaunch(ctx context.Context, in *ReceiverLaunchRequest, opts ...grpc.CallOption) (*ReceiverLaunchResponse, error)
	BackupCreate(ctx context.Context, in *BackupCreateRequest, opts ...grpc.CallOption) (*BackupCreateResponse, error)
	BackupRemove(ctx context.Context, in *BackupRemoveRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	BackupRestore(ctx context.Context, in *BackupRestoreRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	BackupStatus(ctx context.Context, in *BackupStatusRequest, opts ...grpc.CallOption) (*BackupStatusResponse, error)
	Reset(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
	RestoreStatus(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*RestoreStatusResponse, error)
	SnapshotPurge(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
	SnapshotPurgeStatus(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*SnapshotPurgeStatusResponse, error)
	ReplicaRebuildStatus(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ReplicaRebuildStatusResponse, error)
}

type syncAgentServiceClient struct {
	cc *grpc.ClientConn
}

func NewSyncAgentServiceClient(cc *grpc.ClientConn) SyncAgentServiceClient {
	return &syncAgentServiceClient{cc}
}

func (c *syncAgentServiceClient) FileRemove(ctx context.Context, in *FileRemoveRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/ptypes.SyncAgentService/FileRemove", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncAgentServiceClient) FileRename(ctx context.Context, in *FileRenameRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/ptypes.SyncAgentService/FileRename", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncAgentServiceClient) FileSend(ctx context.Context, in *FileSendRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/ptypes.SyncAgentService/FileSend", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncAgentServiceClient) FilesSync(ctx context.Context, in *FilesSyncRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/ptypes.SyncAgentService/FilesSync", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncAgentServiceClient) ReceiverLaunch(ctx context.Context, in *ReceiverLaunchRequest, opts ...grpc.CallOption) (*ReceiverLaunchResponse, error) {
	out := new(ReceiverLaunchResponse)
	err := c.cc.Invoke(ctx, "/ptypes.SyncAgentService/ReceiverLaunch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncAgentServiceClient) BackupCreate(ctx context.Context, in *BackupCreateRequest, opts ...grpc.CallOption) (*BackupCreateResponse, error) {
	out := new(BackupCreateResponse)
	err := c.cc.Invoke(ctx, "/ptypes.SyncAgentService/BackupCreate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncAgentServiceClient) BackupRemove(ctx context.Context, in *BackupRemoveRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/ptypes.SyncAgentService/BackupRemove", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncAgentServiceClient) BackupRestore(ctx context.Context, in *BackupRestoreRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/ptypes.SyncAgentService/BackupRestore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncAgentServiceClient) BackupStatus(ctx context.Context, in *BackupStatusRequest, opts ...grpc.CallOption) (*BackupStatusResponse, error) {
	out := new(BackupStatusResponse)
	err := c.cc.Invoke(ctx, "/ptypes.SyncAgentService/BackupStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncAgentServiceClient) Reset(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/ptypes.SyncAgentService/Reset", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncAgentServiceClient) RestoreStatus(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*RestoreStatusResponse, error) {
	out := new(RestoreStatusResponse)
	err := c.cc.Invoke(ctx, "/ptypes.SyncAgentService/RestoreStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncAgentServiceClient) SnapshotPurge(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/ptypes.SyncAgentService/SnapshotPurge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncAgentServiceClient) SnapshotPurgeStatus(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*SnapshotPurgeStatusResponse, error) {
	out := new(SnapshotPurgeStatusResponse)
	err := c.cc.Invoke(ctx, "/ptypes.SyncAgentService/SnapshotPurgeStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncAgentServiceClient) ReplicaRebuildStatus(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ReplicaRebuildStatusResponse, error) {
	out := new(ReplicaRebuildStatusResponse)
	err := c.cc.Invoke(ctx, "/ptypes.SyncAgentService/ReplicaRebuildStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SyncAgentServiceServer is the server API for SyncAgentService service.
type SyncAgentServiceServer interface {
	FileRemove(context.Context, *FileRemoveRequest) (*empty.Empty, error)
	FileRename(context.Context, *FileRenameRequest) (*empty.Empty, error)
	FileSend(context.Context, *FileSendRequest) (*empty.Empty, error)
	FilesSync(context.Context, *FilesSyncRequest) (*empty.Empty, error)
	ReceiverLaunch(context.Context, *ReceiverLaunchRequest) (*ReceiverLaunchResponse, error)
	BackupCreate(context.Context, *BackupCreateRequest) (*BackupCreateResponse, error)
	BackupRemove(context.Context, *BackupRemoveRequest) (*empty.Empty, error)
	BackupRestore(context.Context, *BackupRestoreRequest) (*empty.Empty, error)
	BackupStatus(context.Context, *BackupStatusRequest) (*BackupStatusResponse, error)
	Reset(context.Context, *empty.Empty) (*empty.Empty, error)
	RestoreStatus(context.Context, *empty.Empty) (*RestoreStatusResponse, error)
	SnapshotPurge(context.Context, *empty.Empty) (*empty.Empty, error)
	SnapshotPurgeStatus(context.Context, *empty.Empty) (*SnapshotPurgeStatusResponse, error)
	ReplicaRebuildStatus(context.Context, *empty.Empty) (*ReplicaRebuildStatusResponse, error)
}

// UnimplementedSyncAgentServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSyncAgentServiceServer struct {
}

func (*UnimplementedSyncAgentServiceServer) FileRemove(ctx context.Context, req *FileRemoveRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FileRemove not implemented")
}
func (*UnimplementedSyncAgentServiceServer) FileRename(ctx context.Context, req *FileRenameRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FileRename not implemented")
}
func (*UnimplementedSyncAgentServiceServer) FileSend(ctx context.Context, req *FileSendRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FileSend not implemented")
}
func (*UnimplementedSyncAgentServiceServer) FilesSync(ctx context.Context, req *FilesSyncRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FilesSync not implemented")
}
func (*UnimplementedSyncAgentServiceServer) ReceiverLaunch(ctx context.Context, req *ReceiverLaunchRequest) (*ReceiverLaunchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReceiverLaunch not implemented")
}
func (*UnimplementedSyncAgentServiceServer) BackupCreate(ctx context.Context, req *BackupCreateRequest) (*BackupCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BackupCreate not implemented")
}
func (*UnimplementedSyncAgentServiceServer) BackupRemove(ctx context.Context, req *BackupRemoveRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BackupRemove not implemented")
}
func (*UnimplementedSyncAgentServiceServer) BackupRestore(ctx context.Context, req *BackupRestoreRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BackupRestore not implemented")
}
func (*UnimplementedSyncAgentServiceServer) BackupStatus(ctx context.Context, req *BackupStatusRequest) (*BackupStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BackupStatus not implemented")
}
func (*UnimplementedSyncAgentServiceServer) Reset(ctx context.Context, req *empty.Empty) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reset not implemented")
}
func (*UnimplementedSyncAgentServiceServer) RestoreStatus(ctx context.Context, req *empty.Empty) (*RestoreStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RestoreStatus not implemented")
}
func (*UnimplementedSyncAgentServiceServer) SnapshotPurge(ctx context.Context, req *empty.Empty) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SnapshotPurge not implemented")
}
func (*UnimplementedSyncAgentServiceServer) SnapshotPurgeStatus(ctx context.Context, req *empty.Empty) (*SnapshotPurgeStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SnapshotPurgeStatus not implemented")
}
func (*UnimplementedSyncAgentServiceServer) ReplicaRebuildStatus(ctx context.Context, req *empty.Empty) (*ReplicaRebuildStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReplicaRebuildStatus not implemented")
}

func RegisterSyncAgentServiceServer(s *grpc.Server, srv SyncAgentServiceServer) {
	s.RegisterService(&_SyncAgentService_serviceDesc, srv)
}

func _SyncAgentService_FileRemove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileRemoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncAgentServiceServer).FileRemove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ptypes.SyncAgentService/FileRemove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncAgentServiceServer).FileRemove(ctx, req.(*FileRemoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncAgentService_FileRename_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileRenameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncAgentServiceServer).FileRename(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ptypes.SyncAgentService/FileRename",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncAgentServiceServer).FileRename(ctx, req.(*FileRenameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncAgentService_FileSend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileSendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncAgentServiceServer).FileSend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ptypes.SyncAgentService/FileSend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncAgentServiceServer).FileSend(ctx, req.(*FileSendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncAgentService_FilesSync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FilesSyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncAgentServiceServer).FilesSync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ptypes.SyncAgentService/FilesSync",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncAgentServiceServer).FilesSync(ctx, req.(*FilesSyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncAgentService_ReceiverLaunch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReceiverLaunchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncAgentServiceServer).ReceiverLaunch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ptypes.SyncAgentService/ReceiverLaunch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncAgentServiceServer).ReceiverLaunch(ctx, req.(*ReceiverLaunchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncAgentService_BackupCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BackupCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncAgentServiceServer).BackupCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ptypes.SyncAgentService/BackupCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncAgentServiceServer).BackupCreate(ctx, req.(*BackupCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncAgentService_BackupRemove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BackupRemoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncAgentServiceServer).BackupRemove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ptypes.SyncAgentService/BackupRemove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncAgentServiceServer).BackupRemove(ctx, req.(*BackupRemoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncAgentService_BackupRestore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BackupRestoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncAgentServiceServer).BackupRestore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ptypes.SyncAgentService/BackupRestore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncAgentServiceServer).BackupRestore(ctx, req.(*BackupRestoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncAgentService_BackupStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BackupStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncAgentServiceServer).BackupStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ptypes.SyncAgentService/BackupStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncAgentServiceServer).BackupStatus(ctx, req.(*BackupStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncAgentService_Reset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncAgentServiceServer).Reset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ptypes.SyncAgentService/Reset",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncAgentServiceServer).Reset(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncAgentService_RestoreStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncAgentServiceServer).RestoreStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ptypes.SyncAgentService/RestoreStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncAgentServiceServer).RestoreStatus(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncAgentService_SnapshotPurge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncAgentServiceServer).SnapshotPurge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ptypes.SyncAgentService/SnapshotPurge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncAgentServiceServer).SnapshotPurge(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncAgentService_SnapshotPurgeStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncAgentServiceServer).SnapshotPurgeStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ptypes.SyncAgentService/SnapshotPurgeStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncAgentServiceServer).SnapshotPurgeStatus(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncAgentService_ReplicaRebuildStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncAgentServiceServer).ReplicaRebuildStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ptypes.SyncAgentService/ReplicaRebuildStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncAgentServiceServer).ReplicaRebuildStatus(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _SyncAgentService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ptypes.SyncAgentService",
	HandlerType: (*SyncAgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FileRemove",
			Handler:    _SyncAgentService_FileRemove_Handler,
		},
		{
			MethodName: "FileRename",
			Handler:    _SyncAgentService_FileRename_Handler,
		},
		{
			MethodName: "FileSend",
			Handler:    _SyncAgentService_FileSend_Handler,
		},
		{
			MethodName: "FilesSync",
			Handler:    _SyncAgentService_FilesSync_Handler,
		},
		{
			MethodName: "ReceiverLaunch",
			Handler:    _SyncAgentService_ReceiverLaunch_Handler,
		},
		{
			MethodName: "BackupCreate",
			Handler:    _SyncAgentService_BackupCreate_Handler,
		},
		{
			MethodName: "BackupRemove",
			Handler:    _SyncAgentService_BackupRemove_Handler,
		},
		{
			MethodName: "BackupRestore",
			Handler:    _SyncAgentService_BackupRestore_Handler,
		},
		{
			MethodName: "BackupStatus",
			Handler:    _SyncAgentService_BackupStatus_Handler,
		},
		{
			MethodName: "Reset",
			Handler:    _SyncAgentService_Reset_Handler,
		},
		{
			MethodName: "RestoreStatus",
			Handler:    _SyncAgentService_RestoreStatus_Handler,
		},
		{
			MethodName: "SnapshotPurge",
			Handler:    _SyncAgentService_SnapshotPurge_Handler,
		},
		{
			MethodName: "SnapshotPurgeStatus",
			Handler:    _SyncAgentService_SnapshotPurgeStatus_Handler,
		},
		{
			MethodName: "ReplicaRebuildStatus",
			Handler:    _SyncAgentService_ReplicaRebuildStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "syncagent.proto",
}
