// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc.proto

/*
Package rpc is a generated protocol buffer package.

It is generated from these files:
	rpc.proto

It has these top-level messages:
	Engine
	Info
	Identity
	Frontend
	Empty
*/
package rpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Engine struct {
	Binary   string   `protobuf:"bytes,1,opt,name=binary" json:"binary,omitempty"`
	Replicas []string `protobuf:"bytes,2,rep,name=replicas" json:"replicas,omitempty"`
}

func (m *Engine) Reset()                    { *m = Engine{} }
func (m *Engine) String() string            { return proto.CompactTextString(m) }
func (*Engine) ProtoMessage()               {}
func (*Engine) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Engine) GetBinary() string {
	if m != nil {
		return m.Binary
	}
	return ""
}

func (m *Engine) GetReplicas() []string {
	if m != nil {
		return m.Replicas
	}
	return nil
}

type Info struct {
	Volume   string `protobuf:"bytes,1,opt,name=volume" json:"volume,omitempty"`
	Frontend string `protobuf:"bytes,2,opt,name=frontend" json:"frontend,omitempty"`
	Endpoint string `protobuf:"bytes,3,opt,name=endpoint" json:"endpoint,omitempty"`
}

func (m *Info) Reset()                    { *m = Info{} }
func (m *Info) String() string            { return proto.CompactTextString(m) }
func (*Info) ProtoMessage()               {}
func (*Info) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Info) GetVolume() string {
	if m != nil {
		return m.Volume
	}
	return ""
}

func (m *Info) GetFrontend() string {
	if m != nil {
		return m.Frontend
	}
	return ""
}

func (m *Info) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

type Identity struct {
	ID string `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
}

func (m *Identity) Reset()                    { *m = Identity{} }
func (m *Identity) String() string            { return proto.CompactTextString(m) }
func (*Identity) ProtoMessage()               {}
func (*Identity) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Identity) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type Frontend struct {
	Frontend string `protobuf:"bytes,1,opt,name=Frontend" json:"Frontend,omitempty"`
}

func (m *Frontend) Reset()                    { *m = Frontend{} }
func (m *Frontend) String() string            { return proto.CompactTextString(m) }
func (*Frontend) ProtoMessage()               {}
func (*Frontend) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Frontend) GetFrontend() string {
	if m != nil {
		return m.Frontend
	}
	return ""
}

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func init() {
	proto.RegisterType((*Engine)(nil), "Engine")
	proto.RegisterType((*Info)(nil), "Info")
	proto.RegisterType((*Identity)(nil), "Identity")
	proto.RegisterType((*Frontend)(nil), "Frontend")
	proto.RegisterType((*Empty)(nil), "Empty")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for LonghornLauncherService service

type LonghornLauncherServiceClient interface {
	UpgradeEngine(ctx context.Context, in *Engine, opts ...grpc.CallOption) (*Empty, error)
	GetInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Info, error)
	StartFrontend(ctx context.Context, in *Identity, opts ...grpc.CallOption) (*Empty, error)
	ShutdownFrontend(ctx context.Context, in *Identity, opts ...grpc.CallOption) (*Empty, error)
	SetFrontend(ctx context.Context, in *Frontend, opts ...grpc.CallOption) (*Empty, error)
}

type longhornLauncherServiceClient struct {
	cc *grpc.ClientConn
}

func NewLonghornLauncherServiceClient(cc *grpc.ClientConn) LonghornLauncherServiceClient {
	return &longhornLauncherServiceClient{cc}
}

func (c *longhornLauncherServiceClient) UpgradeEngine(ctx context.Context, in *Engine, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/LonghornLauncherService/UpgradeEngine", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *longhornLauncherServiceClient) GetInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Info, error) {
	out := new(Info)
	err := grpc.Invoke(ctx, "/LonghornLauncherService/GetInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *longhornLauncherServiceClient) StartFrontend(ctx context.Context, in *Identity, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/LonghornLauncherService/StartFrontend", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *longhornLauncherServiceClient) ShutdownFrontend(ctx context.Context, in *Identity, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/LonghornLauncherService/ShutdownFrontend", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *longhornLauncherServiceClient) SetFrontend(ctx context.Context, in *Frontend, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/LonghornLauncherService/SetFrontend", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for LonghornLauncherService service

type LonghornLauncherServiceServer interface {
	UpgradeEngine(context.Context, *Engine) (*Empty, error)
	GetInfo(context.Context, *Empty) (*Info, error)
	StartFrontend(context.Context, *Identity) (*Empty, error)
	ShutdownFrontend(context.Context, *Identity) (*Empty, error)
	SetFrontend(context.Context, *Frontend) (*Empty, error)
}

func RegisterLonghornLauncherServiceServer(s *grpc.Server, srv LonghornLauncherServiceServer) {
	s.RegisterService(&_LonghornLauncherService_serviceDesc, srv)
}

func _LonghornLauncherService_UpgradeEngine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Engine)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LonghornLauncherServiceServer).UpgradeEngine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/LonghornLauncherService/UpgradeEngine",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LonghornLauncherServiceServer).UpgradeEngine(ctx, req.(*Engine))
	}
	return interceptor(ctx, in, info, handler)
}

func _LonghornLauncherService_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LonghornLauncherServiceServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/LonghornLauncherService/GetInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LonghornLauncherServiceServer).GetInfo(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _LonghornLauncherService_StartFrontend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Identity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LonghornLauncherServiceServer).StartFrontend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/LonghornLauncherService/StartFrontend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LonghornLauncherServiceServer).StartFrontend(ctx, req.(*Identity))
	}
	return interceptor(ctx, in, info, handler)
}

func _LonghornLauncherService_ShutdownFrontend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Identity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LonghornLauncherServiceServer).ShutdownFrontend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/LonghornLauncherService/ShutdownFrontend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LonghornLauncherServiceServer).ShutdownFrontend(ctx, req.(*Identity))
	}
	return interceptor(ctx, in, info, handler)
}

func _LonghornLauncherService_SetFrontend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Frontend)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LonghornLauncherServiceServer).SetFrontend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/LonghornLauncherService/SetFrontend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LonghornLauncherServiceServer).SetFrontend(ctx, req.(*Frontend))
	}
	return interceptor(ctx, in, info, handler)
}

var _LonghornLauncherService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "LonghornLauncherService",
	HandlerType: (*LonghornLauncherServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpgradeEngine",
			Handler:    _LonghornLauncherService_UpgradeEngine_Handler,
		},
		{
			MethodName: "GetInfo",
			Handler:    _LonghornLauncherService_GetInfo_Handler,
		},
		{
			MethodName: "StartFrontend",
			Handler:    _LonghornLauncherService_StartFrontend_Handler,
		},
		{
			MethodName: "ShutdownFrontend",
			Handler:    _LonghornLauncherService_ShutdownFrontend_Handler,
		},
		{
			MethodName: "SetFrontend",
			Handler:    _LonghornLauncherService_SetFrontend_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc.proto",
}

func init() { proto.RegisterFile("rpc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 279 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0x3b, 0x4f, 0xc3, 0x30,
	0x10, 0xc7, 0x9b, 0x94, 0xe6, 0x71, 0xa8, 0x08, 0x79, 0x80, 0x28, 0x53, 0x65, 0x21, 0xe8, 0x94,
	0x01, 0x56, 0xc6, 0x16, 0x14, 0xa9, 0x53, 0x23, 0xd8, 0xd3, 0xe4, 0x9a, 0x58, 0x6a, 0xcf, 0x96,
	0x71, 0x8a, 0xf2, 0x1d, 0xf9, 0x50, 0x28, 0x4f, 0x32, 0xb1, 0xdd, 0xcf, 0xff, 0x87, 0xce, 0x36,
	0xf8, 0x5a, 0x65, 0x91, 0xd2, 0xd2, 0x48, 0xfe, 0x0a, 0xce, 0x96, 0x0a, 0x41, 0xc8, 0xee, 0xc0,
	0x39, 0x08, 0x4a, 0x75, 0x1d, 0x58, 0x2b, 0x6b, 0xed, 0xef, 0x7b, 0x62, 0x21, 0x78, 0x1a, 0xd5,
	0x49, 0x64, 0xe9, 0x57, 0x60, 0xaf, 0xe6, 0x6b, 0x7f, 0x3f, 0x32, 0xff, 0x84, 0xab, 0x98, 0x8e,
	0xb2, 0xc9, 0x5e, 0xe4, 0xa9, 0x3a, 0xe3, 0x90, 0xed, 0xa8, 0xc9, 0x1e, 0xb5, 0x24, 0x83, 0x94,
	0x07, 0x76, 0xab, 0x8c, 0xdc, 0x68, 0x48, 0xb9, 0x92, 0x82, 0x4c, 0x30, 0xef, 0xb4, 0x81, 0x79,
	0x08, 0x5e, 0x9c, 0x23, 0x19, 0x61, 0x6a, 0x76, 0x03, 0x76, 0xbc, 0xe9, 0x7b, 0xed, 0x78, 0xc3,
	0x1f, 0xc1, 0x7b, 0x9b, 0x74, 0x0c, 0x73, 0xef, 0x18, 0x99, 0xbb, 0xb0, 0xd8, 0x9e, 0x95, 0xa9,
	0x9f, 0x7f, 0x2c, 0xb8, 0xdf, 0x49, 0x2a, 0x4a, 0xa9, 0x69, 0x97, 0x56, 0x94, 0x95, 0xa8, 0x13,
	0xd4, 0x17, 0x91, 0x21, 0xe3, 0xb0, 0xfc, 0x50, 0x85, 0x4e, 0x73, 0xec, 0x5f, 0xc1, 0x8d, 0xba,
	0x21, 0x74, 0xa2, 0x36, 0xcd, 0x67, 0x2c, 0x04, 0xf7, 0x1d, 0x4d, 0x7b, 0xcf, 0xfe, 0x30, 0x5c,
	0x44, 0x0d, 0xf2, 0x19, 0x7b, 0x80, 0x65, 0x62, 0x52, 0x6d, 0xc6, 0x8d, 0xfc, 0x68, 0x58, 0x7c,
	0xd2, 0xf0, 0x04, 0xb7, 0x49, 0x59, 0x99, 0x5c, 0x7e, 0xd3, 0xff, 0x46, 0x0e, 0xd7, 0x09, 0x4e,
	0xcb, 0x86, 0xf1, 0xcf, 0x73, 0x70, 0xda, 0x8f, 0x7b, 0xf9, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x9f,
	0x8a, 0xcd, 0xe8, 0xc5, 0x01, 0x00, 0x00,
}
