#!/bin/bash
set -e

source $(dirname $0)/version

if [ "$(git rev-parse --abbrev-ref HEAD)" = "master" ]; then
    COVER="-cover"
    COVERPKG="-coverpkg=github.com/longhorn/longhorn-engine/..."
fi

cd $(dirname $0)/..

mkdir -p bin
go build -tags netgo -ldflags \
	"-X main.Version=$VERSION \
	-X main.GitCommit=$GITCOMMIT \
	-X main.BuildDate=$BUILDDATE \
	-linkmode external -extldflags -static" \
	"$COVER" "$COVERPKG" -o bin/longhorn
