#!/bin/bash

set -e

# if BUILDER_FLAG is set, then the script will exit with the error code
: ${BUILDER_FLAG:=0}

cd $(dirname $0)/..

./generate_grpc.sh
set +e

output=`git diff --stat|grep -e ".pb.go" -e "_pb2.py" -e "_pb2_grpc.py"`
if [ $? -eq 0 ]
then
	echo $output
	echo GRPC generated code is not up to date
	exit $BUILDER_FLAG
fi
