#!/bin/bash
set -e

killall longhorn ssync || true

temp=$(mktemp -d)
temp2=$(mktemp -d)
trap "rm -rf $temp $temp2" EXIT

cd $(dirname $0)/..

if [ ! -x ./bin/longhorn ]; then
    ./scripts/build
fi

./bin/longhorn controller --enable-backend file test-volume &
./bin/longhorn replica $temp &
./bin/longhorn replica --listen localhost:9505 $temp2 &
cd integration
find -depth -name __pycache__ -o -name "*.pyc" -exec rm -rf {} \;
if [ -z "$NO_TEST" ]; then
    tox "$@"
fi
