#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/../package

TAG=${TAG:-${VERSION}}
REPO=${REPO:-rancher}

cp ../bin/longhorn .
docker build -t ${REPO}/longhorn:${TAG} .

echo Built ${REPO}/longhorn:${TAG}
