#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

PROJECT=`basename "$PWD"`

cd ./package

TAG=${TAG:-${VERSION}}
REPO=${REPO:-rancher}

if [ ! -x ../bin/longhorn ]; then
    ../scripts/build
fi

cp ../bin/longhorn* .
cp /usr/src/tgt/pkg/tgt_*.deb .
cp /usr/local/bin/longhorn-engine-launcher .
docker build -t ${REPO}/${PROJECT}:${TAG} .

echo Built ${REPO}/${PROJECT}:${TAG}
