#!/bin/bash

set -e

cd $(dirname $0)/..

./generate_grpc.sh
set +e

output=`git diff --stat|grep -e ".pb.go" -e "_pb2.py" -e "_pb2_grpc.py"`
if [ $? -eq 0 ]
then
	echo $output
	echo GRPC generated code is not up to date
	exit 1
fi
