#!/bin/bash

set -e

cd $(dirname $0)/..
set +e

# TODO: change the branch when longhorn/types PR is merged
git clone https://github.com/FrankYang0529/types.git -b LH-6744 tmp-longhorn-types
cp -r tmp-longhorn-types/rpc-py/ integration/rpc
rm -rf tmp-longhorn-types
echo "Synced longhorn/types/rpc-py to integration/rpc"

output=`git diff --stat|grep -e "_pb2.py" -e "_pb2_grpc.py"`
if [ $? -eq 0 ]
then
	echo $output
	echo Python GRPC generated code is not up to date
	exit 1
fi
