// Code generated by protoc-gen-go. DO NOT EDIT.
// source: controller.proto

package rpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ReplicaMode int32

const (
	ReplicaMode_WO  ReplicaMode = 0
	ReplicaMode_RW  ReplicaMode = 1
	ReplicaMode_ERR ReplicaMode = 2
)

var ReplicaMode_name = map[int32]string{
	0: "WO",
	1: "RW",
	2: "ERR",
}

var ReplicaMode_value = map[string]int32{
	"WO":  0,
	"RW":  1,
	"ERR": 2,
}

func (x ReplicaMode) String() string {
	return proto.EnumName(ReplicaMode_name, int32(x))
}

func (ReplicaMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{0}
}

type Volume struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ReplicaCount         int32    `protobuf:"varint,2,opt,name=replicaCount,proto3" json:"replicaCount,omitempty"`
	Endpoint             string   `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Frontend             string   `protobuf:"bytes,4,opt,name=frontend,proto3" json:"frontend,omitempty"`
	FrontendState        string   `protobuf:"bytes,5,opt,name=frontendState,proto3" json:"frontendState,omitempty"`
	IsRestoring          bool     `protobuf:"varint,6,opt,name=isRestoring,proto3" json:"isRestoring,omitempty"`
	LastRestored         string   `protobuf:"bytes,7,opt,name=lastRestored,proto3" json:"lastRestored,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Volume) Reset()         { *m = Volume{} }
func (m *Volume) String() string { return proto.CompactTextString(m) }
func (*Volume) ProtoMessage()    {}
func (*Volume) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{0}
}

func (m *Volume) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Volume.Unmarshal(m, b)
}
func (m *Volume) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Volume.Marshal(b, m, deterministic)
}
func (m *Volume) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Volume.Merge(m, src)
}
func (m *Volume) XXX_Size() int {
	return xxx_messageInfo_Volume.Size(m)
}
func (m *Volume) XXX_DiscardUnknown() {
	xxx_messageInfo_Volume.DiscardUnknown(m)
}

var xxx_messageInfo_Volume proto.InternalMessageInfo

func (m *Volume) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Volume) GetReplicaCount() int32 {
	if m != nil {
		return m.ReplicaCount
	}
	return 0
}

func (m *Volume) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

func (m *Volume) GetFrontend() string {
	if m != nil {
		return m.Frontend
	}
	return ""
}

func (m *Volume) GetFrontendState() string {
	if m != nil {
		return m.FrontendState
	}
	return ""
}

func (m *Volume) GetIsRestoring() bool {
	if m != nil {
		return m.IsRestoring
	}
	return false
}

func (m *Volume) GetLastRestored() string {
	if m != nil {
		return m.LastRestored
	}
	return ""
}

type ReplicaAddress struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplicaAddress) Reset()         { *m = ReplicaAddress{} }
func (m *ReplicaAddress) String() string { return proto.CompactTextString(m) }
func (*ReplicaAddress) ProtoMessage()    {}
func (*ReplicaAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{1}
}

func (m *ReplicaAddress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplicaAddress.Unmarshal(m, b)
}
func (m *ReplicaAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplicaAddress.Marshal(b, m, deterministic)
}
func (m *ReplicaAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplicaAddress.Merge(m, src)
}
func (m *ReplicaAddress) XXX_Size() int {
	return xxx_messageInfo_ReplicaAddress.Size(m)
}
func (m *ReplicaAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplicaAddress.DiscardUnknown(m)
}

var xxx_messageInfo_ReplicaAddress proto.InternalMessageInfo

func (m *ReplicaAddress) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type ControllerReplica struct {
	Address              *ReplicaAddress `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Mode                 ReplicaMode     `protobuf:"varint,2,opt,name=mode,proto3,enum=rpc.ReplicaMode" json:"mode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ControllerReplica) Reset()         { *m = ControllerReplica{} }
func (m *ControllerReplica) String() string { return proto.CompactTextString(m) }
func (*ControllerReplica) ProtoMessage()    {}
func (*ControllerReplica) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{2}
}

func (m *ControllerReplica) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ControllerReplica.Unmarshal(m, b)
}
func (m *ControllerReplica) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ControllerReplica.Marshal(b, m, deterministic)
}
func (m *ControllerReplica) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ControllerReplica.Merge(m, src)
}
func (m *ControllerReplica) XXX_Size() int {
	return xxx_messageInfo_ControllerReplica.Size(m)
}
func (m *ControllerReplica) XXX_DiscardUnknown() {
	xxx_messageInfo_ControllerReplica.DiscardUnknown(m)
}

var xxx_messageInfo_ControllerReplica proto.InternalMessageInfo

func (m *ControllerReplica) GetAddress() *ReplicaAddress {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *ControllerReplica) GetMode() ReplicaMode {
	if m != nil {
		return m.Mode
	}
	return ReplicaMode_WO
}

type VolumeStartRequest struct {
	ReplicaAddresses     []string `protobuf:"bytes,1,rep,name=replicaAddresses,proto3" json:"replicaAddresses,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VolumeStartRequest) Reset()         { *m = VolumeStartRequest{} }
func (m *VolumeStartRequest) String() string { return proto.CompactTextString(m) }
func (*VolumeStartRequest) ProtoMessage()    {}
func (*VolumeStartRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{3}
}

func (m *VolumeStartRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VolumeStartRequest.Unmarshal(m, b)
}
func (m *VolumeStartRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VolumeStartRequest.Marshal(b, m, deterministic)
}
func (m *VolumeStartRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VolumeStartRequest.Merge(m, src)
}
func (m *VolumeStartRequest) XXX_Size() int {
	return xxx_messageInfo_VolumeStartRequest.Size(m)
}
func (m *VolumeStartRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VolumeStartRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VolumeStartRequest proto.InternalMessageInfo

func (m *VolumeStartRequest) GetReplicaAddresses() []string {
	if m != nil {
		return m.ReplicaAddresses
	}
	return nil
}

type VolumeSnapshotRequest struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Labels               map[string]string `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *VolumeSnapshotRequest) Reset()         { *m = VolumeSnapshotRequest{} }
func (m *VolumeSnapshotRequest) String() string { return proto.CompactTextString(m) }
func (*VolumeSnapshotRequest) ProtoMessage()    {}
func (*VolumeSnapshotRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{4}
}

func (m *VolumeSnapshotRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VolumeSnapshotRequest.Unmarshal(m, b)
}
func (m *VolumeSnapshotRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VolumeSnapshotRequest.Marshal(b, m, deterministic)
}
func (m *VolumeSnapshotRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VolumeSnapshotRequest.Merge(m, src)
}
func (m *VolumeSnapshotRequest) XXX_Size() int {
	return xxx_messageInfo_VolumeSnapshotRequest.Size(m)
}
func (m *VolumeSnapshotRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VolumeSnapshotRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VolumeSnapshotRequest proto.InternalMessageInfo

func (m *VolumeSnapshotRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *VolumeSnapshotRequest) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

type VolumeSnapshotReply struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VolumeSnapshotReply) Reset()         { *m = VolumeSnapshotReply{} }
func (m *VolumeSnapshotReply) String() string { return proto.CompactTextString(m) }
func (*VolumeSnapshotReply) ProtoMessage()    {}
func (*VolumeSnapshotReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{5}
}

func (m *VolumeSnapshotReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VolumeSnapshotReply.Unmarshal(m, b)
}
func (m *VolumeSnapshotReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VolumeSnapshotReply.Marshal(b, m, deterministic)
}
func (m *VolumeSnapshotReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VolumeSnapshotReply.Merge(m, src)
}
func (m *VolumeSnapshotReply) XXX_Size() int {
	return xxx_messageInfo_VolumeSnapshotReply.Size(m)
}
func (m *VolumeSnapshotReply) XXX_DiscardUnknown() {
	xxx_messageInfo_VolumeSnapshotReply.DiscardUnknown(m)
}

var xxx_messageInfo_VolumeSnapshotReply proto.InternalMessageInfo

func (m *VolumeSnapshotReply) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type VolumeRevertRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VolumeRevertRequest) Reset()         { *m = VolumeRevertRequest{} }
func (m *VolumeRevertRequest) String() string { return proto.CompactTextString(m) }
func (*VolumeRevertRequest) ProtoMessage()    {}
func (*VolumeRevertRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{6}
}

func (m *VolumeRevertRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VolumeRevertRequest.Unmarshal(m, b)
}
func (m *VolumeRevertRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VolumeRevertRequest.Marshal(b, m, deterministic)
}
func (m *VolumeRevertRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VolumeRevertRequest.Merge(m, src)
}
func (m *VolumeRevertRequest) XXX_Size() int {
	return xxx_messageInfo_VolumeRevertRequest.Size(m)
}
func (m *VolumeRevertRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VolumeRevertRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VolumeRevertRequest proto.InternalMessageInfo

func (m *VolumeRevertRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type VolumeFrontendStartRequest struct {
	Frontend             string   `protobuf:"bytes,1,opt,name=frontend,proto3" json:"frontend,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VolumeFrontendStartRequest) Reset()         { *m = VolumeFrontendStartRequest{} }
func (m *VolumeFrontendStartRequest) String() string { return proto.CompactTextString(m) }
func (*VolumeFrontendStartRequest) ProtoMessage()    {}
func (*VolumeFrontendStartRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{7}
}

func (m *VolumeFrontendStartRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VolumeFrontendStartRequest.Unmarshal(m, b)
}
func (m *VolumeFrontendStartRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VolumeFrontendStartRequest.Marshal(b, m, deterministic)
}
func (m *VolumeFrontendStartRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VolumeFrontendStartRequest.Merge(m, src)
}
func (m *VolumeFrontendStartRequest) XXX_Size() int {
	return xxx_messageInfo_VolumeFrontendStartRequest.Size(m)
}
func (m *VolumeFrontendStartRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VolumeFrontendStartRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VolumeFrontendStartRequest proto.InternalMessageInfo

func (m *VolumeFrontendStartRequest) GetFrontend() string {
	if m != nil {
		return m.Frontend
	}
	return ""
}

type VolumePrepareRestoreRequest struct {
	LastRestored         string   `protobuf:"bytes,1,opt,name=lastRestored,proto3" json:"lastRestored,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VolumePrepareRestoreRequest) Reset()         { *m = VolumePrepareRestoreRequest{} }
func (m *VolumePrepareRestoreRequest) String() string { return proto.CompactTextString(m) }
func (*VolumePrepareRestoreRequest) ProtoMessage()    {}
func (*VolumePrepareRestoreRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{8}
}

func (m *VolumePrepareRestoreRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VolumePrepareRestoreRequest.Unmarshal(m, b)
}
func (m *VolumePrepareRestoreRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VolumePrepareRestoreRequest.Marshal(b, m, deterministic)
}
func (m *VolumePrepareRestoreRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VolumePrepareRestoreRequest.Merge(m, src)
}
func (m *VolumePrepareRestoreRequest) XXX_Size() int {
	return xxx_messageInfo_VolumePrepareRestoreRequest.Size(m)
}
func (m *VolumePrepareRestoreRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VolumePrepareRestoreRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VolumePrepareRestoreRequest proto.InternalMessageInfo

func (m *VolumePrepareRestoreRequest) GetLastRestored() string {
	if m != nil {
		return m.LastRestored
	}
	return ""
}

type VolumeFinishRestoreRequest struct {
	CurrentRestored      string   `protobuf:"bytes,1,opt,name=currentRestored,proto3" json:"currentRestored,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VolumeFinishRestoreRequest) Reset()         { *m = VolumeFinishRestoreRequest{} }
func (m *VolumeFinishRestoreRequest) String() string { return proto.CompactTextString(m) }
func (*VolumeFinishRestoreRequest) ProtoMessage()    {}
func (*VolumeFinishRestoreRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{9}
}

func (m *VolumeFinishRestoreRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VolumeFinishRestoreRequest.Unmarshal(m, b)
}
func (m *VolumeFinishRestoreRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VolumeFinishRestoreRequest.Marshal(b, m, deterministic)
}
func (m *VolumeFinishRestoreRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VolumeFinishRestoreRequest.Merge(m, src)
}
func (m *VolumeFinishRestoreRequest) XXX_Size() int {
	return xxx_messageInfo_VolumeFinishRestoreRequest.Size(m)
}
func (m *VolumeFinishRestoreRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VolumeFinishRestoreRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VolumeFinishRestoreRequest proto.InternalMessageInfo

func (m *VolumeFinishRestoreRequest) GetCurrentRestored() string {
	if m != nil {
		return m.CurrentRestored
	}
	return ""
}

type ReplicaListReply struct {
	Replicas             []*ControllerReplica `protobuf:"bytes,1,rep,name=replicas,proto3" json:"replicas,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ReplicaListReply) Reset()         { *m = ReplicaListReply{} }
func (m *ReplicaListReply) String() string { return proto.CompactTextString(m) }
func (*ReplicaListReply) ProtoMessage()    {}
func (*ReplicaListReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{10}
}

func (m *ReplicaListReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplicaListReply.Unmarshal(m, b)
}
func (m *ReplicaListReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplicaListReply.Marshal(b, m, deterministic)
}
func (m *ReplicaListReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplicaListReply.Merge(m, src)
}
func (m *ReplicaListReply) XXX_Size() int {
	return xxx_messageInfo_ReplicaListReply.Size(m)
}
func (m *ReplicaListReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplicaListReply.DiscardUnknown(m)
}

var xxx_messageInfo_ReplicaListReply proto.InternalMessageInfo

func (m *ReplicaListReply) GetReplicas() []*ControllerReplica {
	if m != nil {
		return m.Replicas
	}
	return nil
}

type ReplicaPrepareRebuildReply struct {
	Replica              *ControllerReplica `protobuf:"bytes,1,opt,name=replica,proto3" json:"replica,omitempty"`
	Disks                []string           `protobuf:"bytes,2,rep,name=disks,proto3" json:"disks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ReplicaPrepareRebuildReply) Reset()         { *m = ReplicaPrepareRebuildReply{} }
func (m *ReplicaPrepareRebuildReply) String() string { return proto.CompactTextString(m) }
func (*ReplicaPrepareRebuildReply) ProtoMessage()    {}
func (*ReplicaPrepareRebuildReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{11}
}

func (m *ReplicaPrepareRebuildReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplicaPrepareRebuildReply.Unmarshal(m, b)
}
func (m *ReplicaPrepareRebuildReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplicaPrepareRebuildReply.Marshal(b, m, deterministic)
}
func (m *ReplicaPrepareRebuildReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplicaPrepareRebuildReply.Merge(m, src)
}
func (m *ReplicaPrepareRebuildReply) XXX_Size() int {
	return xxx_messageInfo_ReplicaPrepareRebuildReply.Size(m)
}
func (m *ReplicaPrepareRebuildReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplicaPrepareRebuildReply.DiscardUnknown(m)
}

var xxx_messageInfo_ReplicaPrepareRebuildReply proto.InternalMessageInfo

func (m *ReplicaPrepareRebuildReply) GetReplica() *ControllerReplica {
	if m != nil {
		return m.Replica
	}
	return nil
}

func (m *ReplicaPrepareRebuildReply) GetDisks() []string {
	if m != nil {
		return m.Disks
	}
	return nil
}

type JournalListRequest struct {
	Limit                int64    `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JournalListRequest) Reset()         { *m = JournalListRequest{} }
func (m *JournalListRequest) String() string { return proto.CompactTextString(m) }
func (*JournalListRequest) ProtoMessage()    {}
func (*JournalListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{12}
}

func (m *JournalListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JournalListRequest.Unmarshal(m, b)
}
func (m *JournalListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JournalListRequest.Marshal(b, m, deterministic)
}
func (m *JournalListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JournalListRequest.Merge(m, src)
}
func (m *JournalListRequest) XXX_Size() int {
	return xxx_messageInfo_JournalListRequest.Size(m)
}
func (m *JournalListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JournalListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JournalListRequest proto.InternalMessageInfo

func (m *JournalListRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type PortUpdateRequest struct {
	Port                 int32    `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PortUpdateRequest) Reset()         { *m = PortUpdateRequest{} }
func (m *PortUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*PortUpdateRequest) ProtoMessage()    {}
func (*PortUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{13}
}

func (m *PortUpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PortUpdateRequest.Unmarshal(m, b)
}
func (m *PortUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PortUpdateRequest.Marshal(b, m, deterministic)
}
func (m *PortUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PortUpdateRequest.Merge(m, src)
}
func (m *PortUpdateRequest) XXX_Size() int {
	return xxx_messageInfo_PortUpdateRequest.Size(m)
}
func (m *PortUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PortUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PortUpdateRequest proto.InternalMessageInfo

func (m *PortUpdateRequest) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type VersionOutput struct {
	Version                 string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	GitCommit               string   `protobuf:"bytes,2,opt,name=gitCommit,proto3" json:"gitCommit,omitempty"`
	BuildDate               string   `protobuf:"bytes,3,opt,name=buildDate,proto3" json:"buildDate,omitempty"`
	CliAPIVersion           int64    `protobuf:"varint,4,opt,name=cliAPIVersion,proto3" json:"cliAPIVersion,omitempty"`
	CliAPIMinVersion        int64    `protobuf:"varint,5,opt,name=cliAPIMinVersion,proto3" json:"cliAPIMinVersion,omitempty"`
	ControllerAPIVersion    int64    `protobuf:"varint,6,opt,name=controllerAPIVersion,proto3" json:"controllerAPIVersion,omitempty"`
	ControllerAPIMinVersion int64    `protobuf:"varint,7,opt,name=controllerAPIMinVersion,proto3" json:"controllerAPIMinVersion,omitempty"`
	DataFormatVersion       int64    `protobuf:"varint,8,opt,name=dataFormatVersion,proto3" json:"dataFormatVersion,omitempty"`
	DataFormatMinVersion    int64    `protobuf:"varint,9,opt,name=dataFormatMinVersion,proto3" json:"dataFormatMinVersion,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *VersionOutput) Reset()         { *m = VersionOutput{} }
func (m *VersionOutput) String() string { return proto.CompactTextString(m) }
func (*VersionOutput) ProtoMessage()    {}
func (*VersionOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{14}
}

func (m *VersionOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionOutput.Unmarshal(m, b)
}
func (m *VersionOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionOutput.Marshal(b, m, deterministic)
}
func (m *VersionOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionOutput.Merge(m, src)
}
func (m *VersionOutput) XXX_Size() int {
	return xxx_messageInfo_VersionOutput.Size(m)
}
func (m *VersionOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionOutput.DiscardUnknown(m)
}

var xxx_messageInfo_VersionOutput proto.InternalMessageInfo

func (m *VersionOutput) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *VersionOutput) GetGitCommit() string {
	if m != nil {
		return m.GitCommit
	}
	return ""
}

func (m *VersionOutput) GetBuildDate() string {
	if m != nil {
		return m.BuildDate
	}
	return ""
}

func (m *VersionOutput) GetCliAPIVersion() int64 {
	if m != nil {
		return m.CliAPIVersion
	}
	return 0
}

func (m *VersionOutput) GetCliAPIMinVersion() int64 {
	if m != nil {
		return m.CliAPIMinVersion
	}
	return 0
}

func (m *VersionOutput) GetControllerAPIVersion() int64 {
	if m != nil {
		return m.ControllerAPIVersion
	}
	return 0
}

func (m *VersionOutput) GetControllerAPIMinVersion() int64 {
	if m != nil {
		return m.ControllerAPIMinVersion
	}
	return 0
}

func (m *VersionOutput) GetDataFormatVersion() int64 {
	if m != nil {
		return m.DataFormatVersion
	}
	return 0
}

func (m *VersionOutput) GetDataFormatMinVersion() int64 {
	if m != nil {
		return m.DataFormatMinVersion
	}
	return 0
}

type VersionDetailGetReply struct {
	Version              *VersionOutput `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *VersionDetailGetReply) Reset()         { *m = VersionDetailGetReply{} }
func (m *VersionDetailGetReply) String() string { return proto.CompactTextString(m) }
func (*VersionDetailGetReply) ProtoMessage()    {}
func (*VersionDetailGetReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{15}
}

func (m *VersionDetailGetReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionDetailGetReply.Unmarshal(m, b)
}
func (m *VersionDetailGetReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionDetailGetReply.Marshal(b, m, deterministic)
}
func (m *VersionDetailGetReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionDetailGetReply.Merge(m, src)
}
func (m *VersionDetailGetReply) XXX_Size() int {
	return xxx_messageInfo_VersionDetailGetReply.Size(m)
}
func (m *VersionDetailGetReply) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionDetailGetReply.DiscardUnknown(m)
}

var xxx_messageInfo_VersionDetailGetReply proto.InternalMessageInfo

func (m *VersionDetailGetReply) GetVersion() *VersionOutput {
	if m != nil {
		return m.Version
	}
	return nil
}

type Metric struct {
	ReadBandwidth        uint64   `protobuf:"varint,1,opt,name=readBandwidth,proto3" json:"readBandwidth,omitempty"`
	WriteBandwidth       uint64   `protobuf:"varint,2,opt,name=writeBandwidth,proto3" json:"writeBandwidth,omitempty"`
	ReadLatency          uint64   `protobuf:"varint,3,opt,name=readLatency,proto3" json:"readLatency,omitempty"`
	WriteLatency         uint64   `protobuf:"varint,4,opt,name=writeLatency,proto3" json:"writeLatency,omitempty"`
	IOPS                 uint64   `protobuf:"varint,5,opt,name=iOPS,proto3" json:"iOPS,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Metric) Reset()         { *m = Metric{} }
func (m *Metric) String() string { return proto.CompactTextString(m) }
func (*Metric) ProtoMessage()    {}
func (*Metric) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{16}
}

func (m *Metric) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metric.Unmarshal(m, b)
}
func (m *Metric) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metric.Marshal(b, m, deterministic)
}
func (m *Metric) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metric.Merge(m, src)
}
func (m *Metric) XXX_Size() int {
	return xxx_messageInfo_Metric.Size(m)
}
func (m *Metric) XXX_DiscardUnknown() {
	xxx_messageInfo_Metric.DiscardUnknown(m)
}

var xxx_messageInfo_Metric proto.InternalMessageInfo

func (m *Metric) GetReadBandwidth() uint64 {
	if m != nil {
		return m.ReadBandwidth
	}
	return 0
}

func (m *Metric) GetWriteBandwidth() uint64 {
	if m != nil {
		return m.WriteBandwidth
	}
	return 0
}

func (m *Metric) GetReadLatency() uint64 {
	if m != nil {
		return m.ReadLatency
	}
	return 0
}

func (m *Metric) GetWriteLatency() uint64 {
	if m != nil {
		return m.WriteLatency
	}
	return 0
}

func (m *Metric) GetIOPS() uint64 {
	if m != nil {
		return m.IOPS
	}
	return 0
}

type MetricGetReply struct {
	Metric               *Metric  `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MetricGetReply) Reset()         { *m = MetricGetReply{} }
func (m *MetricGetReply) String() string { return proto.CompactTextString(m) }
func (*MetricGetReply) ProtoMessage()    {}
func (*MetricGetReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{17}
}

func (m *MetricGetReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetricGetReply.Unmarshal(m, b)
}
func (m *MetricGetReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetricGetReply.Marshal(b, m, deterministic)
}
func (m *MetricGetReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetricGetReply.Merge(m, src)
}
func (m *MetricGetReply) XXX_Size() int {
	return xxx_messageInfo_MetricGetReply.Size(m)
}
func (m *MetricGetReply) XXX_DiscardUnknown() {
	xxx_messageInfo_MetricGetReply.DiscardUnknown(m)
}

var xxx_messageInfo_MetricGetReply proto.InternalMessageInfo

func (m *MetricGetReply) GetMetric() *Metric {
	if m != nil {
		return m.Metric
	}
	return nil
}

func init() {
	proto.RegisterEnum("rpc.ReplicaMode", ReplicaMode_name, ReplicaMode_value)
	proto.RegisterType((*Volume)(nil), "rpc.Volume")
	proto.RegisterType((*ReplicaAddress)(nil), "rpc.ReplicaAddress")
	proto.RegisterType((*ControllerReplica)(nil), "rpc.ControllerReplica")
	proto.RegisterType((*VolumeStartRequest)(nil), "rpc.VolumeStartRequest")
	proto.RegisterType((*VolumeSnapshotRequest)(nil), "rpc.VolumeSnapshotRequest")
	proto.RegisterMapType((map[string]string)(nil), "rpc.VolumeSnapshotRequest.LabelsEntry")
	proto.RegisterType((*VolumeSnapshotReply)(nil), "rpc.VolumeSnapshotReply")
	proto.RegisterType((*VolumeRevertRequest)(nil), "rpc.VolumeRevertRequest")
	proto.RegisterType((*VolumeFrontendStartRequest)(nil), "rpc.VolumeFrontendStartRequest")
	proto.RegisterType((*VolumePrepareRestoreRequest)(nil), "rpc.VolumePrepareRestoreRequest")
	proto.RegisterType((*VolumeFinishRestoreRequest)(nil), "rpc.VolumeFinishRestoreRequest")
	proto.RegisterType((*ReplicaListReply)(nil), "rpc.ReplicaListReply")
	proto.RegisterType((*ReplicaPrepareRebuildReply)(nil), "rpc.ReplicaPrepareRebuildReply")
	proto.RegisterType((*JournalListRequest)(nil), "rpc.JournalListRequest")
	proto.RegisterType((*PortUpdateRequest)(nil), "rpc.PortUpdateRequest")
	proto.RegisterType((*VersionOutput)(nil), "rpc.VersionOutput")
	proto.RegisterType((*VersionDetailGetReply)(nil), "rpc.VersionDetailGetReply")
	proto.RegisterType((*Metric)(nil), "rpc.Metric")
	proto.RegisterType((*MetricGetReply)(nil), "rpc.MetricGetReply")
}

func init() { proto.RegisterFile("controller.proto", fileDescriptor_ed7f10298fa1d90f) }

var fileDescriptor_ed7f10298fa1d90f = []byte{
	// 1111 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0x6d, 0x6f, 0xdb, 0x36,
	0x10, 0x9e, 0xfc, 0x96, 0xf8, 0xd4, 0x66, 0x2e, 0x9b, 0xa4, 0x86, 0x3b, 0xa0, 0x86, 0x56, 0x64,
	0x5e, 0xd0, 0xb9, 0x81, 0x8b, 0x00, 0x69, 0x91, 0x75, 0xcb, 0x9c, 0xb8, 0xd8, 0x90, 0x20, 0x01,
	0x83, 0xa5, 0x9f, 0x15, 0x8b, 0x49, 0x88, 0xca, 0xa2, 0x46, 0x51, 0x09, 0xfc, 0x0b, 0xf6, 0x65,
	0xbf, 0x63, 0x9f, 0xf7, 0xa3, 0xf6, 0x43, 0x06, 0xbe, 0x48, 0xa6, 0x6c, 0xa9, 0xd8, 0xf6, 0xc9,
	0xe4, 0xc3, 0xe7, 0xee, 0x78, 0xbc, 0xd3, 0x3d, 0x86, 0xce, 0x94, 0x45, 0x82, 0xb3, 0x30, 0x24,
	0x7c, 0x18, 0x73, 0x26, 0x18, 0xaa, 0xf3, 0x78, 0xda, 0x7b, 0x7e, 0xcb, 0xd8, 0x6d, 0x48, 0x5e,
	0x2b, 0xe8, 0x3a, 0xbd, 0x79, 0x4d, 0x66, 0xb1, 0x98, 0x6b, 0x86, 0xf7, 0xb7, 0x03, 0xad, 0x2b,
	0x16, 0xa6, 0x33, 0x82, 0x10, 0x34, 0x22, 0x7f, 0x46, 0xba, 0x4e, 0xdf, 0x19, 0xb4, 0xb1, 0x5a,
	0x23, 0x0f, 0x1e, 0x71, 0x12, 0x87, 0x74, 0xea, 0x8f, 0x59, 0x1a, 0x89, 0x6e, 0xad, 0xef, 0x0c,
	0x9a, 0xb8, 0x80, 0xa1, 0x1e, 0xac, 0x93, 0x28, 0x88, 0x19, 0x8d, 0x44, 0xb7, 0xae, 0x6c, 0xf3,
	0xbd, 0x3c, 0xbb, 0xe1, 0x2c, 0x12, 0x24, 0x0a, 0xba, 0x0d, 0x7d, 0x96, 0xed, 0xd1, 0x4b, 0x78,
	0x9c, 0xad, 0x2f, 0x85, 0x2f, 0x48, 0xb7, 0xa9, 0x08, 0x45, 0x10, 0xf5, 0xc1, 0xa5, 0x09, 0x26,
	0x89, 0x60, 0x9c, 0x46, 0xb7, 0xdd, 0x56, 0xdf, 0x19, 0xac, 0x63, 0x1b, 0x92, 0x77, 0x0c, 0xfd,
	0x44, 0x68, 0x80, 0x04, 0xdd, 0x35, 0xe5, 0xa6, 0x80, 0x79, 0xbb, 0xb0, 0x81, 0xf5, 0x9d, 0x8f,
	0x82, 0x80, 0x93, 0x24, 0x41, 0x5d, 0x58, 0xf3, 0xf5, 0xd2, 0x24, 0x9c, 0x6d, 0xbd, 0x3b, 0x78,
	0x32, 0xce, 0x1f, 0xd2, 0x58, 0xa1, 0xef, 0x8a, 0x74, 0x77, 0xf4, 0x74, 0xc8, 0xe3, 0xe9, 0xb0,
	0xe8, 0x34, 0xf7, 0x81, 0x5e, 0x42, 0x63, 0xc6, 0x02, 0xa2, 0xde, 0x6b, 0x63, 0xd4, 0xb1, 0xb9,
	0x67, 0x2c, 0x20, 0x58, 0x9d, 0x7a, 0x3f, 0x02, 0xd2, 0x6f, 0x7f, 0x29, 0x7c, 0x2e, 0x30, 0xf9,
	0x2d, 0x25, 0x89, 0x40, 0xbb, 0xd0, 0xe1, 0x05, 0xb7, 0x44, 0xc6, 0xac, 0x0f, 0xda, 0x78, 0x05,
	0xf7, 0xfe, 0x74, 0x60, 0xcb, 0xb8, 0x88, 0xfc, 0x38, 0xb9, 0x63, 0xb9, 0x97, 0xb2, 0x6a, 0xbe,
	0x87, 0x56, 0xe8, 0x5f, 0x93, 0x30, 0xe9, 0xd6, 0xfa, 0xf5, 0x81, 0x3b, 0xda, 0x51, 0xf7, 0x2a,
	0xb5, 0x1f, 0x9e, 0x2a, 0xe2, 0x49, 0x24, 0xf8, 0x1c, 0x1b, 0xab, 0xde, 0x5b, 0x70, 0x2d, 0x18,
	0x75, 0xa0, 0xfe, 0x89, 0xcc, 0x4d, 0x04, 0xb9, 0x44, 0x9b, 0xd0, 0xbc, 0xf7, 0xc3, 0x54, 0xe7,
	0xdd, 0xc6, 0x7a, 0xf3, 0xae, 0x76, 0xe0, 0x78, 0xdf, 0xc2, 0xd3, 0xe5, 0x38, 0x71, 0x38, 0x2f,
	0xbb, 0xe5, 0x82, 0x8a, 0xc9, 0x3d, 0xe1, 0x9f, 0x4b, 0xc8, 0x3b, 0x80, 0x9e, 0xa6, 0x4e, 0x16,
	0x3d, 0xb3, 0xb0, 0xb0, 0x9b, 0xcf, 0x29, 0x36, 0x9f, 0x77, 0x04, 0xcf, 0xb5, 0xe5, 0x05, 0x27,
	0xb1, 0xcf, 0x89, 0xe9, 0x94, 0xcc, 0x74, 0xb9, 0xa7, 0x9c, 0x92, 0x9e, 0x9a, 0xe4, 0xc1, 0x69,
	0x44, 0x93, 0xbb, 0x25, 0x0f, 0x03, 0xf8, 0x72, 0x9a, 0x72, 0x4e, 0xa2, 0x65, 0x27, 0xcb, 0xb0,
	0x37, 0x81, 0x8e, 0x69, 0x8d, 0x53, 0x9a, 0x98, 0x77, 0x19, 0xc1, 0xba, 0xa9, 0xb5, 0xae, 0xbd,
	0x3b, 0xda, 0x56, 0xb5, 0x5a, 0x69, 0x4c, 0x9c, 0xf3, 0xbc, 0x00, 0x7a, 0x06, 0xcc, 0x73, 0xba,
	0x4e, 0x69, 0x18, 0x68, 0x8f, 0x7b, 0xb0, 0x66, 0x98, 0xa6, 0x81, 0xab, 0x1c, 0x66, 0x34, 0x59,
	0xcc, 0x80, 0x26, 0x9f, 0x74, 0xb3, 0xb4, 0xb1, 0xde, 0x78, 0xbb, 0x80, 0x7e, 0x61, 0x29, 0x8f,
	0xfc, 0x50, 0xdf, 0x56, 0x67, 0xbb, 0x09, 0xcd, 0x90, 0xce, 0xa8, 0x50, 0xbe, 0xeb, 0x58, 0x6f,
	0xbc, 0x6f, 0xe0, 0xc9, 0x05, 0xe3, 0xe2, 0xd7, 0x38, 0xf0, 0x05, 0xb1, 0xea, 0x18, 0x33, 0xae,
	0x99, 0x4d, 0xac, 0xd6, 0xde, 0xef, 0x75, 0x78, 0x7c, 0x45, 0x78, 0x42, 0x59, 0x74, 0x9e, 0x8a,
	0x38, 0x15, 0xf2, 0xf3, 0xbc, 0xd7, 0x40, 0xf6, 0x79, 0x9a, 0x2d, 0xfa, 0x0a, 0xda, 0xb7, 0x54,
	0x8c, 0xd9, 0x4c, 0x86, 0xd3, 0x7d, 0xb6, 0x00, 0xe4, 0xa9, 0x4a, 0xfa, 0x58, 0x0e, 0x14, 0x3d,
	0x8d, 0x16, 0x80, 0x1c, 0x39, 0xd3, 0x90, 0x1e, 0x5d, 0xfc, 0x6c, 0x82, 0xa9, 0x99, 0x54, 0xc7,
	0x45, 0x50, 0x7e, 0x80, 0x1a, 0x38, 0xa3, 0x51, 0x46, 0x6c, 0x2a, 0xe2, 0x0a, 0x8e, 0x46, 0xb0,
	0xb9, 0x98, 0xba, 0x96, 0xe3, 0x96, 0xe2, 0x97, 0x9e, 0xa1, 0x03, 0x78, 0x56, 0xc0, 0xad, 0x30,
	0x6b, 0xca, 0xac, 0xea, 0x18, 0xbd, 0x82, 0x27, 0x81, 0x2f, 0xfc, 0x09, 0xe3, 0x33, 0x5f, 0x64,
	0x36, 0xeb, 0xca, 0x66, 0xf5, 0x40, 0xde, 0x6d, 0x01, 0x5a, 0x41, 0xda, 0xfa, 0x6e, 0x65, 0x67,
	0xde, 0x09, 0x6c, 0x99, 0xe5, 0x31, 0x11, 0x3e, 0x0d, 0x3f, 0x10, 0xd3, 0x91, 0xaf, 0x8a, 0x05,
	0x71, 0x47, 0x48, 0x0f, 0x0f, 0xbb, 0x6a, 0x79, 0x91, 0xbc, 0xbf, 0x1c, 0x68, 0x9d, 0x11, 0xc1,
	0xe9, 0x54, 0xbe, 0x39, 0x27, 0x7e, 0xf0, 0x93, 0x1f, 0x05, 0x0f, 0x34, 0x10, 0x77, 0xca, 0xbc,
	0x81, 0x8b, 0x20, 0xda, 0x81, 0x8d, 0x07, 0x4e, 0x05, 0x59, 0xd0, 0x6a, 0x8a, 0xb6, 0x84, 0x4a,
	0x39, 0x90, 0x86, 0xa7, 0xbe, 0x20, 0xd1, 0x74, 0xae, 0x2a, 0xdc, 0xc0, 0x36, 0x24, 0x3f, 0x5d,
	0x65, 0x93, 0x51, 0x1a, 0x8a, 0x52, 0xc0, 0x64, 0x0f, 0xd2, 0xf3, 0x8b, 0x4b, 0x55, 0xd5, 0x06,
	0x56, 0x6b, 0x6f, 0x1f, 0x36, 0xf4, 0x8d, 0xf3, 0x94, 0xbf, 0x86, 0xd6, 0x4c, 0x21, 0x26, 0x63,
	0x57, 0x65, 0xac, 0x49, 0xd8, 0x1c, 0xed, 0xee, 0x80, 0x6b, 0x0d, 0x76, 0xd4, 0x82, 0xda, 0xc7,
	0xf3, 0xce, 0x17, 0xf2, 0x17, 0x7f, 0xec, 0x38, 0x68, 0x0d, 0xea, 0x27, 0x18, 0x77, 0x6a, 0xa3,
	0x3f, 0xc0, 0x96, 0x95, 0x4b, 0xc2, 0xef, 0xe9, 0x94, 0xa0, 0x3d, 0x68, 0xeb, 0x19, 0xf2, 0x81,
	0x08, 0xb4, 0x3d, 0xd4, 0x4a, 0x3d, 0xcc, 0x94, 0x7a, 0x78, 0x22, 0x95, 0xba, 0xe7, 0x5a, 0x63,
	0x1a, 0xbd, 0x01, 0xd7, 0xd2, 0x0c, 0xf4, 0xcc, 0x1e, 0xe1, 0xd6, 0xf0, 0x2b, 0x1a, 0xed, 0xc3,
	0x86, 0xa1, 0xdc, 0xa5, 0x22, 0x60, 0x0f, 0xd1, 0xbf, 0x8b, 0x35, 0xc9, 0xcd, 0xcc, 0xd0, 0x46,
	0xbd, 0x6a, 0xc5, 0xe8, 0x75, 0x4b, 0xcf, 0xe4, 0x43, 0xee, 0xc3, 0x23, 0x7b, 0xa2, 0x23, 0x9b,
	0x59, 0x18, 0xf2, 0xc5, 0xf0, 0xe3, 0x4c, 0x08, 0x0a, 0xd3, 0x1d, 0xbd, 0xb0, 0x38, 0x65, 0x73,
	0xbf, 0xe8, 0xe4, 0x7b, 0xd8, 0x5e, 0xa2, 0xfe, 0xa7, 0x27, 0x38, 0x81, 0xcd, 0x32, 0x9d, 0x40,
	0x7d, 0x8b, 0x54, 0x2a, 0x21, 0x55, 0xa9, 0xd8, 0x5a, 0x51, 0x4c, 0xa5, 0x44, 0x45, 0x8a, 0x4e,
	0x0e, 0xf3, 0x56, 0x93, 0xa3, 0xb7, 0xf2, 0xfe, 0x5b, 0xf6, 0xbf, 0x8d, 0x85, 0xa4, 0xbc, 0x05,
	0x30, 0x98, 0xec, 0xb5, 0xb2, 0xbf, 0x2f, 0xbd, 0x0a, 0x49, 0x40, 0x87, 0xf0, 0xd8, 0x2c, 0xc7,
	0x9c, 0xc8, 0x39, 0xfa, 0x3f, 0xad, 0x8f, 0x49, 0x48, 0xaa, 0xad, 0x4b, 0xb3, 0x41, 0x3f, 0xe4,
	0xd6, 0x5a, 0x46, 0x50, 0x45, 0x98, 0xca, 0xf0, 0x67, 0xb0, 0x55, 0x2a, 0x8b, 0xe5, 0xd7, 0x78,
	0x61, 0x83, 0x65, 0x3a, 0x3a, 0x86, 0x4d, 0x73, 0x7a, 0x45, 0x38, 0xbd, 0x99, 0x7f, 0xd6, 0x5b,
	0xd5, 0x9d, 0xde, 0x83, 0x6b, 0x89, 0xa8, 0xf9, 0x88, 0x57, 0x65, 0xb5, 0xf2, 0x51, 0x0e, 0x01,
	0x16, 0xc2, 0x6a, 0x5e, 0x64, 0x45, 0x69, 0x2b, 0xad, 0x27, 0xd0, 0x59, 0x9e, 0xf1, 0x95, 0xcd,
	0xd4, 0xb3, 0xa7, 0xfc, 0x92, 0x24, 0xbc, 0x83, 0x76, 0x3e, 0x31, 0x2b, 0x1d, 0x3c, 0xb5, 0x86,
	0x66, 0x66, 0xb9, 0xe7, 0x5c, 0xb7, 0x14, 0xed, 0xcd, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x29,
	0x33, 0x65, 0x77, 0xb4, 0x0c, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ControllerServiceClient is the client API for ControllerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ControllerServiceClient interface {
	VolumeGet(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Volume, error)
	VolumeStart(ctx context.Context, in *VolumeStartRequest, opts ...grpc.CallOption) (*Volume, error)
	VolumeShutdown(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Volume, error)
	VolumeSnapshot(ctx context.Context, in *VolumeSnapshotRequest, opts ...grpc.CallOption) (*VolumeSnapshotReply, error)
	VolumeRevert(ctx context.Context, in *VolumeRevertRequest, opts ...grpc.CallOption) (*Volume, error)
	VolumeFrontendStart(ctx context.Context, in *VolumeFrontendStartRequest, opts ...grpc.CallOption) (*Volume, error)
	VolumeFrontendShutdown(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Volume, error)
	VolumePrepareRestore(ctx context.Context, in *VolumePrepareRestoreRequest, opts ...grpc.CallOption) (*Volume, error)
	VolumeFinishRestore(ctx context.Context, in *VolumeFinishRestoreRequest, opts ...grpc.CallOption) (*Volume, error)
	ReplicaList(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ReplicaListReply, error)
	ReplicaGet(ctx context.Context, in *ReplicaAddress, opts ...grpc.CallOption) (*ControllerReplica, error)
	ReplicaCreate(ctx context.Context, in *ReplicaAddress, opts ...grpc.CallOption) (*ControllerReplica, error)
	ReplicaDelete(ctx context.Context, in *ReplicaAddress, opts ...grpc.CallOption) (*empty.Empty, error)
	ReplicaUpdate(ctx context.Context, in *ControllerReplica, opts ...grpc.CallOption) (*ControllerReplica, error)
	ReplicaPrepareRebuild(ctx context.Context, in *ReplicaAddress, opts ...grpc.CallOption) (*ReplicaPrepareRebuildReply, error)
	ReplicaVerifyRebuild(ctx context.Context, in *ReplicaAddress, opts ...grpc.CallOption) (*ControllerReplica, error)
	JournalList(ctx context.Context, in *JournalListRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	PortUpdate(ctx context.Context, in *PortUpdateRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	VersionDetailGet(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*VersionDetailGetReply, error)
	MetricGet(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (ControllerService_MetricGetClient, error)
}

type controllerServiceClient struct {
	cc *grpc.ClientConn
}

func NewControllerServiceClient(cc *grpc.ClientConn) ControllerServiceClient {
	return &controllerServiceClient{cc}
}

func (c *controllerServiceClient) VolumeGet(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Volume, error) {
	out := new(Volume)
	err := c.cc.Invoke(ctx, "/rpc.ControllerService/VolumeGet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) VolumeStart(ctx context.Context, in *VolumeStartRequest, opts ...grpc.CallOption) (*Volume, error) {
	out := new(Volume)
	err := c.cc.Invoke(ctx, "/rpc.ControllerService/VolumeStart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) VolumeShutdown(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Volume, error) {
	out := new(Volume)
	err := c.cc.Invoke(ctx, "/rpc.ControllerService/VolumeShutdown", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) VolumeSnapshot(ctx context.Context, in *VolumeSnapshotRequest, opts ...grpc.CallOption) (*VolumeSnapshotReply, error) {
	out := new(VolumeSnapshotReply)
	err := c.cc.Invoke(ctx, "/rpc.ControllerService/VolumeSnapshot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) VolumeRevert(ctx context.Context, in *VolumeRevertRequest, opts ...grpc.CallOption) (*Volume, error) {
	out := new(Volume)
	err := c.cc.Invoke(ctx, "/rpc.ControllerService/VolumeRevert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) VolumeFrontendStart(ctx context.Context, in *VolumeFrontendStartRequest, opts ...grpc.CallOption) (*Volume, error) {
	out := new(Volume)
	err := c.cc.Invoke(ctx, "/rpc.ControllerService/VolumeFrontendStart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) VolumeFrontendShutdown(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Volume, error) {
	out := new(Volume)
	err := c.cc.Invoke(ctx, "/rpc.ControllerService/VolumeFrontendShutdown", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) VolumePrepareRestore(ctx context.Context, in *VolumePrepareRestoreRequest, opts ...grpc.CallOption) (*Volume, error) {
	out := new(Volume)
	err := c.cc.Invoke(ctx, "/rpc.ControllerService/VolumePrepareRestore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) VolumeFinishRestore(ctx context.Context, in *VolumeFinishRestoreRequest, opts ...grpc.CallOption) (*Volume, error) {
	out := new(Volume)
	err := c.cc.Invoke(ctx, "/rpc.ControllerService/VolumeFinishRestore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) ReplicaList(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ReplicaListReply, error) {
	out := new(ReplicaListReply)
	err := c.cc.Invoke(ctx, "/rpc.ControllerService/ReplicaList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) ReplicaGet(ctx context.Context, in *ReplicaAddress, opts ...grpc.CallOption) (*ControllerReplica, error) {
	out := new(ControllerReplica)
	err := c.cc.Invoke(ctx, "/rpc.ControllerService/ReplicaGet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) ReplicaCreate(ctx context.Context, in *ReplicaAddress, opts ...grpc.CallOption) (*ControllerReplica, error) {
	out := new(ControllerReplica)
	err := c.cc.Invoke(ctx, "/rpc.ControllerService/ReplicaCreate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) ReplicaDelete(ctx context.Context, in *ReplicaAddress, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/rpc.ControllerService/ReplicaDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) ReplicaUpdate(ctx context.Context, in *ControllerReplica, opts ...grpc.CallOption) (*ControllerReplica, error) {
	out := new(ControllerReplica)
	err := c.cc.Invoke(ctx, "/rpc.ControllerService/ReplicaUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) ReplicaPrepareRebuild(ctx context.Context, in *ReplicaAddress, opts ...grpc.CallOption) (*ReplicaPrepareRebuildReply, error) {
	out := new(ReplicaPrepareRebuildReply)
	err := c.cc.Invoke(ctx, "/rpc.ControllerService/ReplicaPrepareRebuild", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) ReplicaVerifyRebuild(ctx context.Context, in *ReplicaAddress, opts ...grpc.CallOption) (*ControllerReplica, error) {
	out := new(ControllerReplica)
	err := c.cc.Invoke(ctx, "/rpc.ControllerService/ReplicaVerifyRebuild", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) JournalList(ctx context.Context, in *JournalListRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/rpc.ControllerService/JournalList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) PortUpdate(ctx context.Context, in *PortUpdateRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/rpc.ControllerService/PortUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) VersionDetailGet(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*VersionDetailGetReply, error) {
	out := new(VersionDetailGetReply)
	err := c.cc.Invoke(ctx, "/rpc.ControllerService/VersionDetailGet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) MetricGet(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (ControllerService_MetricGetClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ControllerService_serviceDesc.Streams[0], "/rpc.ControllerService/MetricGet", opts...)
	if err != nil {
		return nil, err
	}
	x := &controllerServiceMetricGetClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ControllerService_MetricGetClient interface {
	Recv() (*MetricGetReply, error)
	grpc.ClientStream
}

type controllerServiceMetricGetClient struct {
	grpc.ClientStream
}

func (x *controllerServiceMetricGetClient) Recv() (*MetricGetReply, error) {
	m := new(MetricGetReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ControllerServiceServer is the server API for ControllerService service.
type ControllerServiceServer interface {
	VolumeGet(context.Context, *empty.Empty) (*Volume, error)
	VolumeStart(context.Context, *VolumeStartRequest) (*Volume, error)
	VolumeShutdown(context.Context, *empty.Empty) (*Volume, error)
	VolumeSnapshot(context.Context, *VolumeSnapshotRequest) (*VolumeSnapshotReply, error)
	VolumeRevert(context.Context, *VolumeRevertRequest) (*Volume, error)
	VolumeFrontendStart(context.Context, *VolumeFrontendStartRequest) (*Volume, error)
	VolumeFrontendShutdown(context.Context, *empty.Empty) (*Volume, error)
	VolumePrepareRestore(context.Context, *VolumePrepareRestoreRequest) (*Volume, error)
	VolumeFinishRestore(context.Context, *VolumeFinishRestoreRequest) (*Volume, error)
	ReplicaList(context.Context, *empty.Empty) (*ReplicaListReply, error)
	ReplicaGet(context.Context, *ReplicaAddress) (*ControllerReplica, error)
	ReplicaCreate(context.Context, *ReplicaAddress) (*ControllerReplica, error)
	ReplicaDelete(context.Context, *ReplicaAddress) (*empty.Empty, error)
	ReplicaUpdate(context.Context, *ControllerReplica) (*ControllerReplica, error)
	ReplicaPrepareRebuild(context.Context, *ReplicaAddress) (*ReplicaPrepareRebuildReply, error)
	ReplicaVerifyRebuild(context.Context, *ReplicaAddress) (*ControllerReplica, error)
	JournalList(context.Context, *JournalListRequest) (*empty.Empty, error)
	PortUpdate(context.Context, *PortUpdateRequest) (*empty.Empty, error)
	VersionDetailGet(context.Context, *empty.Empty) (*VersionDetailGetReply, error)
	MetricGet(*empty.Empty, ControllerService_MetricGetServer) error
}

// UnimplementedControllerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedControllerServiceServer struct {
}

func (*UnimplementedControllerServiceServer) VolumeGet(ctx context.Context, req *empty.Empty) (*Volume, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VolumeGet not implemented")
}
func (*UnimplementedControllerServiceServer) VolumeStart(ctx context.Context, req *VolumeStartRequest) (*Volume, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VolumeStart not implemented")
}
func (*UnimplementedControllerServiceServer) VolumeShutdown(ctx context.Context, req *empty.Empty) (*Volume, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VolumeShutdown not implemented")
}
func (*UnimplementedControllerServiceServer) VolumeSnapshot(ctx context.Context, req *VolumeSnapshotRequest) (*VolumeSnapshotReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VolumeSnapshot not implemented")
}
func (*UnimplementedControllerServiceServer) VolumeRevert(ctx context.Context, req *VolumeRevertRequest) (*Volume, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VolumeRevert not implemented")
}
func (*UnimplementedControllerServiceServer) VolumeFrontendStart(ctx context.Context, req *VolumeFrontendStartRequest) (*Volume, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VolumeFrontendStart not implemented")
}
func (*UnimplementedControllerServiceServer) VolumeFrontendShutdown(ctx context.Context, req *empty.Empty) (*Volume, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VolumeFrontendShutdown not implemented")
}
func (*UnimplementedControllerServiceServer) VolumePrepareRestore(ctx context.Context, req *VolumePrepareRestoreRequest) (*Volume, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VolumePrepareRestore not implemented")
}
func (*UnimplementedControllerServiceServer) VolumeFinishRestore(ctx context.Context, req *VolumeFinishRestoreRequest) (*Volume, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VolumeFinishRestore not implemented")
}
func (*UnimplementedControllerServiceServer) ReplicaList(ctx context.Context, req *empty.Empty) (*ReplicaListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReplicaList not implemented")
}
func (*UnimplementedControllerServiceServer) ReplicaGet(ctx context.Context, req *ReplicaAddress) (*ControllerReplica, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReplicaGet not implemented")
}
func (*UnimplementedControllerServiceServer) ReplicaCreate(ctx context.Context, req *ReplicaAddress) (*ControllerReplica, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReplicaCreate not implemented")
}
func (*UnimplementedControllerServiceServer) ReplicaDelete(ctx context.Context, req *ReplicaAddress) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReplicaDelete not implemented")
}
func (*UnimplementedControllerServiceServer) ReplicaUpdate(ctx context.Context, req *ControllerReplica) (*ControllerReplica, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReplicaUpdate not implemented")
}
func (*UnimplementedControllerServiceServer) ReplicaPrepareRebuild(ctx context.Context, req *ReplicaAddress) (*ReplicaPrepareRebuildReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReplicaPrepareRebuild not implemented")
}
func (*UnimplementedControllerServiceServer) ReplicaVerifyRebuild(ctx context.Context, req *ReplicaAddress) (*ControllerReplica, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReplicaVerifyRebuild not implemented")
}
func (*UnimplementedControllerServiceServer) JournalList(ctx context.Context, req *JournalListRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JournalList not implemented")
}
func (*UnimplementedControllerServiceServer) PortUpdate(ctx context.Context, req *PortUpdateRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PortUpdate not implemented")
}
func (*UnimplementedControllerServiceServer) VersionDetailGet(ctx context.Context, req *empty.Empty) (*VersionDetailGetReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VersionDetailGet not implemented")
}
func (*UnimplementedControllerServiceServer) MetricGet(req *empty.Empty, srv ControllerService_MetricGetServer) error {
	return status.Errorf(codes.Unimplemented, "method MetricGet not implemented")
}

func RegisterControllerServiceServer(s *grpc.Server, srv ControllerServiceServer) {
	s.RegisterService(&_ControllerService_serviceDesc, srv)
}

func _ControllerService_VolumeGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).VolumeGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.ControllerService/VolumeGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).VolumeGet(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_VolumeStart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VolumeStartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).VolumeStart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.ControllerService/VolumeStart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).VolumeStart(ctx, req.(*VolumeStartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_VolumeShutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).VolumeShutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.ControllerService/VolumeShutdown",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).VolumeShutdown(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_VolumeSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VolumeSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).VolumeSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.ControllerService/VolumeSnapshot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).VolumeSnapshot(ctx, req.(*VolumeSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_VolumeRevert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VolumeRevertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).VolumeRevert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.ControllerService/VolumeRevert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).VolumeRevert(ctx, req.(*VolumeRevertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_VolumeFrontendStart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VolumeFrontendStartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).VolumeFrontendStart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.ControllerService/VolumeFrontendStart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).VolumeFrontendStart(ctx, req.(*VolumeFrontendStartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_VolumeFrontendShutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).VolumeFrontendShutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.ControllerService/VolumeFrontendShutdown",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).VolumeFrontendShutdown(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_VolumePrepareRestore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VolumePrepareRestoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).VolumePrepareRestore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.ControllerService/VolumePrepareRestore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).VolumePrepareRestore(ctx, req.(*VolumePrepareRestoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_VolumeFinishRestore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VolumeFinishRestoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).VolumeFinishRestore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.ControllerService/VolumeFinishRestore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).VolumeFinishRestore(ctx, req.(*VolumeFinishRestoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_ReplicaList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).ReplicaList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.ControllerService/ReplicaList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).ReplicaList(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_ReplicaGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplicaAddress)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).ReplicaGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.ControllerService/ReplicaGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).ReplicaGet(ctx, req.(*ReplicaAddress))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_ReplicaCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplicaAddress)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).ReplicaCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.ControllerService/ReplicaCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).ReplicaCreate(ctx, req.(*ReplicaAddress))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_ReplicaDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplicaAddress)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).ReplicaDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.ControllerService/ReplicaDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).ReplicaDelete(ctx, req.(*ReplicaAddress))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_ReplicaUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ControllerReplica)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).ReplicaUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.ControllerService/ReplicaUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).ReplicaUpdate(ctx, req.(*ControllerReplica))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_ReplicaPrepareRebuild_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplicaAddress)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).ReplicaPrepareRebuild(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.ControllerService/ReplicaPrepareRebuild",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).ReplicaPrepareRebuild(ctx, req.(*ReplicaAddress))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_ReplicaVerifyRebuild_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplicaAddress)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).ReplicaVerifyRebuild(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.ControllerService/ReplicaVerifyRebuild",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).ReplicaVerifyRebuild(ctx, req.(*ReplicaAddress))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_JournalList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JournalListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).JournalList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.ControllerService/JournalList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).JournalList(ctx, req.(*JournalListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_PortUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PortUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).PortUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.ControllerService/PortUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).PortUpdate(ctx, req.(*PortUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_VersionDetailGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).VersionDetailGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.ControllerService/VersionDetailGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).VersionDetailGet(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_MetricGet_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(empty.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ControllerServiceServer).MetricGet(m, &controllerServiceMetricGetServer{stream})
}

type ControllerService_MetricGetServer interface {
	Send(*MetricGetReply) error
	grpc.ServerStream
}

type controllerServiceMetricGetServer struct {
	grpc.ServerStream
}

func (x *controllerServiceMetricGetServer) Send(m *MetricGetReply) error {
	return x.ServerStream.SendMsg(m)
}

var _ControllerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.ControllerService",
	HandlerType: (*ControllerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VolumeGet",
			Handler:    _ControllerService_VolumeGet_Handler,
		},
		{
			MethodName: "VolumeStart",
			Handler:    _ControllerService_VolumeStart_Handler,
		},
		{
			MethodName: "VolumeShutdown",
			Handler:    _ControllerService_VolumeShutdown_Handler,
		},
		{
			MethodName: "VolumeSnapshot",
			Handler:    _ControllerService_VolumeSnapshot_Handler,
		},
		{
			MethodName: "VolumeRevert",
			Handler:    _ControllerService_VolumeRevert_Handler,
		},
		{
			MethodName: "VolumeFrontendStart",
			Handler:    _ControllerService_VolumeFrontendStart_Handler,
		},
		{
			MethodName: "VolumeFrontendShutdown",
			Handler:    _ControllerService_VolumeFrontendShutdown_Handler,
		},
		{
			MethodName: "VolumePrepareRestore",
			Handler:    _ControllerService_VolumePrepareRestore_Handler,
		},
		{
			MethodName: "VolumeFinishRestore",
			Handler:    _ControllerService_VolumeFinishRestore_Handler,
		},
		{
			MethodName: "ReplicaList",
			Handler:    _ControllerService_ReplicaList_Handler,
		},
		{
			MethodName: "ReplicaGet",
			Handler:    _ControllerService_ReplicaGet_Handler,
		},
		{
			MethodName: "ReplicaCreate",
			Handler:    _ControllerService_ReplicaCreate_Handler,
		},
		{
			MethodName: "ReplicaDelete",
			Handler:    _ControllerService_ReplicaDelete_Handler,
		},
		{
			MethodName: "ReplicaUpdate",
			Handler:    _ControllerService_ReplicaUpdate_Handler,
		},
		{
			MethodName: "ReplicaPrepareRebuild",
			Handler:    _ControllerService_ReplicaPrepareRebuild_Handler,
		},
		{
			MethodName: "ReplicaVerifyRebuild",
			Handler:    _ControllerService_ReplicaVerifyRebuild_Handler,
		},
		{
			MethodName: "JournalList",
			Handler:    _ControllerService_JournalList_Handler,
		},
		{
			MethodName: "PortUpdate",
			Handler:    _ControllerService_PortUpdate_Handler,
		},
		{
			MethodName: "VersionDetailGet",
			Handler:    _ControllerService_VersionDetailGet_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "MetricGet",
			Handler:       _ControllerService_MetricGet_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "controller.proto",
}
