#!/bin/bash

is_controller=0
fe=0
frontend=
for i in "$@"
do
        if [ $fe -eq 1 ]
        then
                frontend=$i
                break
        fi
        case $i in
                controller)
                        is_controller=1
                        ;;
                --frontend)
                        fe=1
                        ;;
                *)
                        ;;
        esac
done

if [ $is_controller -eq 1 ]; then
        mount --rbind /host/dev /dev

        if [ "$frontend" == "tcmu" ]
        then
                echo "Prepare for TCMU"
                if [ ! -d /sys/kernel/config ]; then
                        modprobe target_core_user
                fi
                mount -t configfs none /sys/kernel/config
        fi
fi

exec longhorn "$@"
