#!/usr/bin/env bash

BASE_IMAGE_DIR_LIST=( `ls /base_image` )
if [ ${#BASE_IMAGE_DIR_LIST[@]} -ne 1 ]; then
  echo "/base_image directory must contain exactly one base image file"
  exit 1
fi
IMAGE_FILE="/base_image/${BASE_IMAGE_DIR_LIST[0]}"

COMMAND=$1
shift
if [ "${COMMAND}" == "replica" ]; then
    /cmd/longhorn ${COMMAND} --backing-file ${IMAGE_FILE}  "$@"
elif [ "${COMMAND}" == "sync-agent" ]; then
    /cmd/longhorn ${COMMAND} "$@"
else
    echo "Bad command: ${COMMAND}"
    exit 1
fi
