#!/bin/bash

set -x

if [ "$1" == "controller" ]; then
  if [ ! -d /sys/kernel/config ]; then
    modprobe target_core_user
  fi

  mount --rbind /host/dev /dev
  mount -t configfs none /sys/kernel/config
fi

exec longhorn "$@"
