#!/usr/bin/env bash

BASE_IMAGE_DIR_LIST=( `ls /base_image` )
if [ ${#BASE_IMAGE_DIR_LIST[@]} -ne 1 ]; then
  echo "/base_image directory must contain exactly one base image file"
  exit 1
fi
IMAGE_FILE="/base_image/${BASE_IMAGE_DIR_LIST[0]}"


/cmd/longhorn replica --backing-file ${IMAGE_FILE}  "$@"