#!/bin/bash

set -x
set -e
mount --rbind /host/dev /dev

volume=$1
size=$2
frontend=$3

if [ -z $volume ]
then
        echo "Usage: launch-simple-longhorn <volume_name> <frontend> "
        echo "<volume_name>: Required. User defined volume name"
        echo "<frontend>: Optional. By default 'tgt-blockdev'. "
	exit -1
fi

if [ -z $size ]
then
        echo Use default size 1g
        size="1g"
fi

if [ -z $frontend ]
then
        echo Use default frontend TGT block device
        frontend="tgt-blockdev"
fi

launcher="longhorn controller"
extra_opts=""

[[ $frontend == "tgt-"* ]] && launcher="longhorn-engine-launcher start" && extra_opts="--size $size"

longhorn replica --size $size --listen localhost:9502 /volume/ &
sleep 1
exec $launcher --listen 0.0.0.0:9501 --frontend $frontend --replica tcp://localhost:9502 $extra_opts $volume
