#!/bin/bash

if [ "$1" == "controller" ]; then
        mount --rbind /host/dev /dev

        frontend=
        fe=0
        for i in "$@"
        do
                if [ $fe -eq 1 ]
                then
                        frontend=$i
                        break
                fi
                case $i in
                        --frontend)
                                fe=1
                                ;;
                        *)
                                ;;
                esac
        done

        if [ "$frontend" == "tcmu" ]
        then
                echo "Prepare for TCMU"
                if [ ! -d /sys/kernel/config ]; then
                        modprobe target_core_user
                fi
                mount -t configfs none /sys/kernel/config
        fi
fi

exec longhorn "$@"
