name: Link-Backport-PR-Issue

on:
  pull_request:
    types: [opened]
    branches:
      - master
      - "v*"

jobs:
  call-workflow:
    uses: longhorn/longhorn/.github/workflows/backport-pr.yml@666fcb2f9b7d50b60936ba517f71c44df4e4d482 # v1.11.2
