name: Link-Backport-PR-Issue

on:
  pull_request:
    types: [opened]
    branches:
      - master
      - "v*"

jobs:
  call-workflow:
    uses: longhorn/longhorn/.github/workflows/backport-pr.yml@f349c091c50700cb6cb8a4df8aaa29ea214bdd48 # v1.12.1
