name: Link-Backport-PR-Issue

on:
  pull_request:
    types: [opened]
    branches:
      - master
      - "v*"

jobs:
  call-workflow:
    uses: longhorn/longhorn/.github/workflows/backport-pr.yml@eb3790253449e3577b4acb88b5620258cde6d747 # v1.11.1
