name: Codespell

on:
  pull_request:
    branches:
    - master
    - main
    - "v*.*.*"

jobs:
  codespell:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      with:
        fetch-depth: 1
    - name: Check code spell
      uses: codespell-project/actions-codespell@8f01853be192eb0f849a5c7d721450e7a467c579 # v2
      with:
        check_filenames: true
        skip: "./proto,*/**.yaml,*/**.yml,./scripts,./integration,./vendor,MAINTAINERS,LICENSE,go.mod,go.sum"
