name: fossa
on:
  push:
    branches:
      - master
      - v*
    tags:
      - v*
  workflow_dispatch: {}

permissions: {}

jobs:
  fossa-scan:
    if: github.repository == 'longhorn/longhorn-engine' # FOSSA is not intended to run on forks.
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      FOSSA_API_KEY: ${{ secrets.FOSSA_API_KEY }}
    steps:
      - name: "Checkout code"
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: "Run FOSSA Scan"
        uses: fossas/fossa-action@29693cc50323968e039056be419b32989fc5880c # v2.0.0 # Use a specific version if locking is preferred
        with:
          api-key: ${{ secrets.FOSSA_API_KEY }}
          project: longhorn-engine
