name: 'Close stale issues and PRs'

on:
  workflow_dispatch:
  schedule:
  - cron: '30 1 * * *'

jobs:
  call-workflow:
    uses: longhorn/longhorn/.github/workflows/stale.yaml@efbad602f33c24a747185575eab29d2189390acd
