name: 'Close stale issues and PRs'

on:
  workflow_dispatch:
  schedule:
  - cron: '30 1 * * *'

jobs:
  call-workflow:
    uses: longhorn/longhorn/.github/workflows/stale.yaml@eb3790253449e3577b4acb88b5620258cde6d747 # v1.11.1
